### ISSUE TITLE
Problem with riparian plotting

### ISSUE THREAD

**Issue by esud1** [jtlovell/GENESPACE#10]
Hi there, 

Thank you for this very useful tool! 
I am having a bit of a problem while plotting the riparian plot. 
It returns the error message like this: 

```
        Reading hits ... Done!
        Generating plot coordinates ... Done!
        Rendering plot ... Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  :
  unable to start device X11cairo
In addition: Warning message:
In (function (display = "", width, height, pointsize, gamma, bg,  :
  unable to open connection to X11 display ''
```

FYI, I had no problem running the example - I can get the final example plot. 

Do you have any ideas about what went wrong? 

Thanks, 
Edi

**Comment by jtlovell** [comment]
not sure ... this seems like a graphics device problem. Can you try writing to pdf?

```
pdf("ripTest.pdf")
plot_riparianHits(yourArgsHere)
dev.off()
```

**Comment by esud1** [comment]
Thanks for the help.
It works well with writing to pdf!
