### ISSUE TITLE
Error in plot_riparian

### ISSUE THREAD

**Issue by bbista** [jtlovell/GENESPACE#101]
Hello,
I am trying to make custom plots using the following commands:
TSC_order=as.character(1:25)
ripDat <- plot_riparian( gsParam = gsParam,
                         refGenome = "3_TSC",
                         forceRecalcBlocks = FALSE,pdfFile = "3_TSC_bp.pdf",
                         palette = customPal,braidAlpha = .85,chrFill = "lightgrey",addThemes = ggthemes,
                         customRefChrOrder = TSC_order
)

I get the following error: 
Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  : 
  Incompatible join types: x.refChr (character) and i.refChr (integer)

3_TSC has 25 chromosomes named 1 to 25.

I still get the same error when I remove customRefChrOrder 

Also, run_genespace does generate the riparian plot for 3_TSC. Its only when I use plot_riparian i get the error

Best,
Basanta

**Comment by bbista** [comment]
Hello,
I was able to work around it by labelling one of the chromosomes "25_" instead of 25.
I think it was not working because all the chromosomes had numbers for its name and the software read it as integer and not character.

Best,
B

**Comment by jtlovell** [comment]
OK. Thanks for letting me know.
