### ISSUE TITLE
Riparian plot

### ISSUE THREAD

**Issue by Ljay4** [jtlovell/GENESPACE#102]
I made a riparian plot to compare several citrus species, which have 9 chromosomes. However, only the species that I set as reference showed all the 9 chromosomes, and the others only had the chromosomes that have syntenies with the neighboring species. Is there a way to show all the chromosomes, regardless the number of syntenies? Is there a cutoff of the number of syntenies for the chromosomes to be displayed? Also, most the braids on my plot appear to be blocks, and can the thickness of braids be adjusted? Thank you!

[ripdat.pdf](https://github.com/jtlovell/GENESPACE/files/11627180/ripdat.pdf)

**Comment by Ljay4** [comment]
Yes, I used the default settings, and did not give it intervals. By
the way, I have a few hundreds genes to be plotted in each species.

**Comment by jtlovell** [comment]
can you attach the plot produced internally (should have the name /riparian/$genomeID_geneOrder.rip.pdf).

**Comment by Ljay4** [comment]
Hi there,

I've attached some rip plots, and there are some more plots much similar to
these.

I also included the code I used to make the plots. Towards the end are what
I used to modify the graph.

Thanks a lot!

**Comment by jtlovell** [comment]
Not seeing the plots

**Comment by jtlovell** [comment]
still don't see them

**Comment by Ljay4** [comment]
Hi John,

I pasted the graphs in this email, instead of attaching it. Can you see it
this time? The syntenies looks quite blocky. I'm still trying to improve
them. Your help is much appreciated!

Thank you,
Jay

**Comment by jtlovell** [comment]
I think you need to post it right in the github thread, not as an email.

**Comment by Ljay4** [comment]
I'm attaching a plot that I wanted to improve. See if you can see it now. Thanks!
[Glauca_bp.rip.pdf](https://github.com/jtlovell/GENESPACE/files/11738148/Glauca_bp.rip.pdf)

**Comment by jtlovell** [comment]
eesh. that looks terrible. What do the dotplots look like?

**Comment by Ljay4** [comment]
It didn't generate any dot plot. The folder is empty

**Comment by jtlovell** [comment]
huh. do these genomes have a ton of tiny scaffolds? What did the QC dialog print during the first step?

**Comment by Ljay4** [comment]
3 genomes have minor scaffolds, and 2 don't. I don't recall what the QC said. I can run it tomorrow to see what it has. I've attached my script for your ref. 
[genespace_workflow.txt](https://github.com/jtlovell/GENESPACE/files/11738678/genespace_workflow.txt)
