### ISSUE TITLE
Is the pangenome not what you are looking for? See figure 1 [here](https://elifesciences.org/articles/78526#content).

### ISSUE THREAD

**Issue by xiaoyezao** [jtlovell/GENESPACE#103]
Is the pangenome not what you are looking for? See figure 1 [here](https://elifesciences.org/articles/78526#content). 
Since you are only interested in syntenic orthogroups, that may be too complex. In that case, you can just read in the results/gffWithOgs.txt.gz file and parse via the `synOG` column. If you want one syntenic orthogroup per line, 
```
library(data.table)
g <- fread("results/gffWithOgs.txt.gz")
synOgs <- dcast(g, synOG ~ genome, value.var = "id", fun.aggregate = list)
```

_Originally posted by @jtlovell in https://github.com/jtlovell/GENESPACE/issues/31#issuecomment-1245520697_

**Comment by jtlovell** [comment]
Yes, this can happen in polyploids ... are these all haploid genomes?

**Comment by jtlovell** [comment]
I guess it depends how you want to think about arrays and duplicated genes across the genome. GENESPACE assumes that, for example, if a gene duplicates in a tandem array, then spreads to other places in the genome through WGDs etc that all its decendents should be represented and placed into all of the unique syntenic positions of that gene family.
