### ISSUE TITLE
Difference between physical-position based and gene-rank order based plotting

### ISSUE THREAD

**Issue by alexvasilikop** [jtlovell/GENESPACE#105]
Hello,

I generated the riparian plots for my 5 genomes (6 chromosomes each) that have a signature of palaeotetraploidy (ancient WGD before the species diverged, chrom 1 is homoeologous to 4, 2 to 5, and 3 to 6 in the fig below). The resulting riparian plots show this homoeologous signal (see below, the species on the top is the most distantly related so there cannot be a clear separation between homoeologs and orthologs due to the evolutionary distance?). Any suggestions on how to get rid of the secondary signal? I ran the analyses with genomes as haploid (blksize=5, ngaps=10). Increasing the blksize and reducing the ngaps parameter perhaps? I ran the analyses without an outgroup and asked all species to be used in synteny analyses.

In addition I do not understand why the plot based on gene-rank order vs physical position differs. You will see for example that 
for the 4th species and 5th chromosome, the ribbons start not at the beginning of the chromosome  when the plot is based on physical position. Why is this the case? I would assume that irrespective of what scale you use the ribbons should start at the same chromosome coordinates?

I am using v. 1.2.3

Thanks
Alex

![gene_rank](https://github.com/jtlovell/GENESPACE/assets/29930069/12320b72-0f55-472d-a81b-48e58884d863)

![phys_pos](https://github.com/jtlovell/GENESPACE/assets/29930069/2be421e6-3b1d-40f2-b6a9-1d2cc1479a53)

**Comment by jtlovell** [comment]
"Get rid of the secondary signal" - I'm not sure I follow. If one of your genomes has a WGD, then the homeologs will be equally related to the other genomes and one is not secondary to the other. We go over this situation in the results (Fig3) and last methods section of the GENESPACE article. 

"I do not understand why the plot based on gene-rank order vs physical position differs." Both plots start at the first position. If you have a large area without syntenic genes, the left start will be at 1 in gene rank order and much more than that in basepairs.

**Comment by alexvasilikop** [comment]
There is a whole genome duplication yes but for all genomes in the plot (the first 3 chromosomes for each genome are the homoeologs of chromosomes 4, 5, 6) , but the WGD predates the speciation event. Therefore I assume only orthologous chromosomes should be depicted in the riparian plot as the homoeologs of different species show higher level of degradation (due to the very ancient WGD event). Insn't the aim of the software to identify the orthologous regions from paralogous? Then the connection to the homoeologs should not be shown I suppose. this is what I am trying to do

**Comment by jtlovell** [comment]
I think there must be another WGD that you did not expect in the terminal branch to that top genome. Look at the kmer histogram (or the self dotplots) of that genome and see if you have signals of a wgd.

**Comment by alexvasilikop** [comment]
I  don't see how there can be an additional WGD. They all have 6 chromosomes and there is 1-1 relationship. if you plot the blocks and not the regions, it is clear that the secondary connections (blocks) among non-orthologous chromosomes are scarce.
![image](https://github.com/jtlovell/GENESPACE/assets/29930069/18a966a6-fb57-47be-9aca-8511b4f128d0)

Also the dotplot shows 1 homoeologous chromosome for each of the first 3 chromosomes
![image](https://github.com/jtlovell/GENESPACE/assets/29930069/46924c86-9873-4475-bcc0-e22875d96442)

Could it be that there has been homoeologous recombination after the speciation event in the top genome that distorts the orthologous signal?

**Comment by jtlovell** [comment]
hmm. were all the genomes annotated the same way? There is something up with that top genome that is causing blocks to be retained - this could be because it has fewer genes than the others, or that there are assembly issues. Or, more likely, it could have diverged closer to the WGD than the others? You can always increase the block size and decrease the number of gaps to remove smaller dispersed blocks.

**Comment by alexvasilikop** [comment]
They were all annotated with the same method. The top genome is more distantly related to the others and yes probably an earlier offshoot in the phylogeny after the WGD. Anyway thanks. 

One more question to make sure I fully understand the plot. Do the ribbons show only collinear regions mapped on to the reference genome (bottom in this case)? For example would a unique collinear block that is not in the reference genome (bottom genome) but exists between species 2 and 3, would it appear on the plot? I noticed that when I swap the reference there might be some additional ribbons in the plot.



best

**Comment by alexvasilikop** [comment]
Ok by increasing the number of blocks and decreasing the number of gaps, I was able to get rid of the paralogous signal.
![image](https://github.com/jtlovell/GENESPACE/assets/29930069/73471b1e-6c15-45e4-819a-f1012e91085c)

**Comment by alexvasilikop** [comment]
Hello John,

I still have some trouble understanding parts of the visualization of the riparian plots even after reading the paper and documentation. In the plot above I assume that the braids correspond to syntenic orthogroups (1 copy per genome per OG) plotted based on the position of these genes along the chromosomes of different genomes. Only OGs present in the reference genome are shown (bottom genome is reference)? Please correct me if I am wrong.

However I do not understand why some chromosome parts show these missing connections. see for example the denoted regions below.

Chromosome 3 of species 3 connects almost end to end with chromosome 3 of species 4 but not with chromosome 3 of species 2. So does this mean than synteny is not shared between species 2 and 4 for these terminal orthogroups?. If the plot shows shared OG across all species then why are the OGs at the end of chrom 3 of species 3 do not connect to chrom 3 of species 2? How can I interpret synteny between genomes that are not directly connected in the plot (e.g., between genome 2 and 5)
![test](https://github.com/jtlovell/GENESPACE/assets/29930069/d6138ab8-4f9a-4219-8f78-46b907e560fe)

Many thanks for your help
Alex

**Comment by jtlovell** [comment]
If you set `useOrder = TRUE` do you still get this? My guess is that these regions are gene-poor and lack synteny from a gene-space perspective. You can sanity check this by running `plot_2genomes` for your reference and one of the others (you'll need to add `minimap2` to your conda env to run this).
