### ISSUE TITLE
Documentation for files and their columns in results and other directories

### ISSUE THREAD

**Issue by alexvasilikop** [jtlovell/GENESPACE#106]
Hello,

Thanks again for developing some useful tools. Is it possible that you can add some documentation-description of the output files in the results directory? Or is there somewhere where I can find this info?

In particular I am referring to the following files and their columns:
syntenicBlock_coordinates.csv
syntenicRegion_coordinates.csv
Orthogroups.tsv
N0.tsv
combBed.txt

Same thing applies for the pangenome, syntenic hits directories.

Also I have some difficulty interpreting the legend for the dotplots (see below).
what does score > 50, 11/11−gene x/y windows (heatmap range: 2−5+ hits/window) mean?
Thanks
Alex

![image](https://github.com/jtlovell/GENESPACE/assets/29930069/977d19a5-95b3-4e80-88ba-6322d1d26024)

**Comment by jtlovell** [comment]
Yeah, the documentation needs to be better and will eventually get there in the help file; however, the descriptions are in the various sub-functions and fully described in the [tutorial](https://htmlpreview.github.io/?https://github.com/jtlovell/tutorials/blob/main/genespaceGuide.html) tho.

**Comment by alexvasilikop** [comment]
Thanks, the score is referring to bitscore here?

**Comment by jtlovell** [comment]
diamond bitscore, yes.
