### ISSUE TITLE
 NOTE! Genomes flagged *** have > 5% of genes in over-dispersed orthogroups.

### ISSUE THREAD

**Issue by alexvasilikop** [jtlovell/GENESPACE#107]
Hello,

During the execution of the pipeline, the follwoing warning pops up

```
Flagging over-dispered OGs
	...species1       : 1087 genes in  65 OGs hit > 8 unique places 
 	...species2       : 2011 genes in 120 OGs hit > 8 unique places ***
 	...species3       :  300 genes in  18 OGs hit > 8 unique places 
 	...species4       :  1603 genes in  77 OGs hit > 8 unique places 
 	...species5       :  677 genes in  22 OGs hit > 8 unique places 
        NOTE! Genomes flagged *** have > 5% of genes in over-dispersed orthogroups. These are likely not great annotations, or the
                synteny run contains un-specified WGDs. Regardless, these should be examined carefully
```

What does this mean exactly?
thanks
Alex

**Comment by jtlovell** [comment]
This means that for species 2, there are 2011 genes in 120 orthogroups (~18 genes per orthogroup) that are distributed in > 8 syntenic positions across the genome. This can happen if you say that ploidy is lower than it is, or if you have a problematic gene annotation, potentially including lots of low-q gene models. 5% is an arbitrary threshold. I would look at species 1, 2, and 4.

**Comment by alexvasilikop** [comment]
great thanks
