### ISSUE TITLE
Plot only secondary hits - Riparian

### ISSUE THREAD

**Issue by alexvasilikop** [jtlovell/GENESPACE#109]
Hello,

Is there any functionality for plotting only the secondary hits in the riparian plot (eg homoeologs after masking the primary hits?).

Thanks
Alex

**Comment by jtlovell** [comment]
I think your best bet is to manually subset the hits, then use `gghits`. There is no functionality for this in `plot_riparian`.

**Comment by alexvasilikop** [comment]
great thanks
