### ISSUE TITLE
Naming convention for block IDs?

### ISSUE THREAD

**Issue by Snodgras** [jtlovell/GENESPACE#110]
Hello!

I'm trying to split ancient allopolyploid genomes into their two subgenomes based on their synteny to a diploid reference and each other. So for each syntenic block in the diploid reference, it should match twice in the ancient polyploid.  Between ancient polyploid genomes, that same block should have 1 best match such that the block for subgenome 1 in genome A matches to subgenome 1 in genome B-- not subgenome 2. 

I am trying to use the block IDs from `riparian/_phasedBlks.csv` to do this. However, I'm not sure what the naming convention is for the block IDs. For instance, if I have 4 genomes A-D, given that synteny is determined pairwise, would the following `blkID` strings indicate the same block?: `GenomeA_vs_GenomeB: 1_1` and `GenomeC_vs_GenomeD: 1_1` Or are these different blocks from separate pair-wise comparisons? Or something else? What does the `_1` or `_2` mean at the end of the ID string? 

Thank you for your time!

**Comment by jtlovell** [comment]
the naming convention is [$queryGenomeID]_vs_[$targetGenomeID]: [$sytenicRegionNumber]_[$syntenicBlockNumberWithinRegion]. 

It won't have any bearing on subgenomes. 
Determining subgenomes from GENESPACE-default output will be very difficult. A diploid relative should have synteny and orthology to both subgenomes regardless of subgenome bias. You would want to query the blast results and parse bit scores (or similar) to find mapping bias. 

Sorry I can't be of more help. 
John
