### ISSUE TITLE
Parsing self-formatted BEDs

### ISSUE THREAD

**Issue by NatJWalker-Hale** [jtlovell/GENESPACE#111]
Hi @jtlovell,

Thanks for the really nice tool. I just wanted to double check a couple of errors relating to parsing one's own BEDs. Specifically, while the documentation suggests that BEDs with more than four columns will have the additional columns ignored, I don't think this is currently the case because `data.table::fread()` still fails despite `select = 1:4`.

When trying to run from my own peptide files and BEDs (in `wd/peptide` and `wd/bed` respectively), `init_genespace()` returns:
```
Error in bd$id : $ operator is invalid for atomic vectors
```
which seems to derive from lines 440 and 441 of `utils.R`, concerning the output of `read_bed()`. Running the `fread()` call from `read_bed()` on my own gives the following error:
```
Error in fread(filepath, verbose = FALSE, showProgress = FALSE, select = 1:4,  : 
  colClasses= is an unnamed vector of types, length 4, but there are 6 columns in the input. To specify types for a subset of columns, you can use a named vector, list format, or specify types using select= instead of colClasses=. Please see examples in ?fread.
```
which suggests that colClasses does not respect the post-`select = 1:4` parsing from `fread()`.

Editing my BEDs to contain only the first four columns fixes this issue.

I guess this isn't so much a problem, but you might just change the documentation to instruct people to input BEDs with only four columns?

By the way, I don't think `data.table` is listed in the R dependencies (unless I've missed it somewhere).

Thanks again!

Nat

**Comment by jtlovell** [comment]
This is likely a bug that was brought to my attention recently in #108. 
I haven't yet written a fix to it, but if you drop the extra bed columns, it should work. If not, lmk. 

This bug will be fixed in the next push, which should be by the end of July.

**Comment by NatJWalker-Hale** [comment]
Thanks @jtlovell! Can't believe I missed that while perusing the closed 😅 Can confirm dropping extra columns fixes the issue.

**Comment by jtlovell** [comment]
Great. Thanks for letting me know.
