### ISSUE TITLE
Showing smaller contigs

### ISSUE THREAD

**Issue by johannesnicolaus** [jtlovell/GENESPACE#115]
Hi, thanks for the really nice package!

I have a problem where my some of the smaller contigs are not seen. I am working with a compact genome and so the Y chromosomes are very small, is there a way to show them? Is there a threshold somewhere that I can edit?

**Comment by JKing2000** [comment]
I think what you are looking for can be achieved by changing the "minChrLen2plot" setting, described in section 3.5 of the tutorial here:
https://htmlpreview.github.io/?https://github.com/jtlovell/tutorials/blob/main/riparianGuide.html

**Comment by johannesnicolaus** [comment]
> I think what you are looking for can be achieved by changing the "minChrLen2plot" setting, described in section 3.5 of the tutorial here: https://htmlpreview.github.io/?https://github.com/jtlovell/tutorials/blob/main/riparianGuide.html

I don't know how i missed that! Thank you so much!!

**Comment by johannesnicolaus** [comment]
I don't know if I should reopen this issue, but I changed `minChrLen2plot` to 0, but some of the contigs were still not visible, is there any other argument that I should change?  I checked combBed.txt and the contigs seem to also be present...

**Comment by JKing2000** [comment]
I think this is because the smaller Y contigs do not have synteny with anything and are therefore not plotted. The Y can be quite different between species.

With that being said, I would be interested to know from the owner if there is an option to provide a list of specific Chromosome/contigs from each species to plot even if it doesn't have synteny with any thing else, perhaps have them plotted at the right-most position for each species.

I would appreciate it if you could keep this thread open so that the owner can see it, thanks.

**Comment by johannesnicolaus** [comment]
Thanks, I'm still new and not too familiar to this kind of analysis. I'm currently analyzing cryptic species which in principle should have some degree of synteny. For example, I see synteny on the Y chromosome for 2/3 species.

Do you know if I can make the computation (alignment?) for syntenic regions less stringent? I tried to change `blkRadius` but I don't think that really changed anything...

**Comment by jtlovell** [comment]
Thanks @JKing2000 ... that is an accurate response. 
I am in the process of writing another riparian plotting function to handle whole-genome windowed alignments. This will for sure keep all chromosomes, regardless of synteny. However, I do not envision modifying the current `plot_riparian` to keep all chromosomes, as the point of that function is to track synteny. 

I'll tag this thread when I update the new functions, but I doubt this will be until the fall sometime.
