### ISSUE TITLE
Question about changes in synteny when adding more genomes

### ISSUE THREAD

**Issue by JKing2000** [jtlovell/GENESPACE#118]
Hi, I am comparing synteny between different genome assemblies of a species. There is a small inversion between Hap1 and Hap2 of a particular assembly (minimap2 alignment confirms this) and this is shown in the first synteny plot (image1), but this inversion is eventually lost when I have more genomes in the genespace run (after addition of the 6th or 7th genome from different assembler) (image2). What could be the reasoning behind this?

image1
![image1](https://github.com/jtlovell/GENESPACE/assets/105471690/49a5e2a9-bf1e-4647-b7fb-990cbd7d30b7)

image2
![image2](https://github.com/jtlovell/GENESPACE/assets/105471690/94a4a747-2e36-4eb9-875f-eeea862209e2)

**Comment by jtlovell** [comment]
Were you able to figure this out? Sounds fishy.

**Comment by JKing2000** [comment]
No I was not able to figure out why this happened. It does sound fishy that synteny between two genomes can change when new genomes are added.
Something to add is that the inversion occurs between the X and Y specific region, (X and Y chromosome each in different haplotype) and I know that synteny can often be weird in the sex chromosomes. But still unsure why it would change.

**Comment by jtlovell** [comment]
Without the data for this, I can't really comment - if you want to send me an email with the data, feel free and I'll have a look
