### ISSUE TITLE
clean_windows() dotplot has swapped X Y axis title

### ISSUE THREAD

**Issue by JKing2000** [jtlovell/GENESPACE#120]
It seems the dotplots generated from clean_windows() has the right X and Y axis label but wrong axis title (subject and query swapped).
my command is as follows:
p <- clean_windows(wd =wd, nCores = 16, faFiles = c("genome1.fa", "genome2.fa", "genome3.fa"))

The version of minimap2 I use is 2.24

**Comment by jtlovell** [comment]
Thanks for this! yup - I see the bug. 
Sorry about the delayed response ... will update this when I push v1.4 later this month.
