### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ofedrigo** [jtlovell/GENESPACE#124]
I get this error message while installing:

`devtools::install_github("jtlovell/GENESPACE")
Downloading GitHub repo jtlovell/GENESPACE@HEAD
Skipping 1 packages not available: Biostrings
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpslNqYf/remotes8f8e35e1b8090/jtlovell-GENESPACE-893f902/DESCRIPTION’ ...
─  preparing ‘GENESPACE’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘GENESPACE_1.3.1.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘GENESPACE’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘seqinfo’ is not exported by 'namespace:Biostrings'
Execution halted
ERROR: lazy loading failed for package ‘GENESPACE’
* removing ‘/usr/local/lib/R/site-library/GENESPACE’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpslNqYf/file8f8e34e3fa8bc/GENESPACE_1.3.1.tar.gz’ had non-zero exit status`

all dependencies seem to be properly installed. This is what I did:

install.packages("devtools")
install.packages("BiocManager")
BiocManager::install(c("Biostrings", "rtracklayer"))
devtools::install_github("jtlovell/GENESPACE")

Thanks,

Olivier

**Comment by jtlovell** [comment]
I'm not sure - its saying you don't have a valid "Biostrings" install. Can you confirm that this is the case?
