### ISSUE TITLE
Highlight the gene of interest across the chromosome

### ISSUE THREAD

**Issue by HobbitBaba** [jtlovell/GENESPACE#127]
Hi there,
Thanks for this nice tool. I have a small question about the riparian plot.

Is it possible to just plot individuals genes across all crhomosomes and all genomes? I have a bed file with genes under selection and I'd like to just draw a line from their position in one genome to their position in the other, but with the syntenic blocks grayed out underneath. Is this possible?

Like the attach figure.
![SmartSelect_20231016-213041_Chrome](https://github.com/jtlovell/GENESPACE/assets/148108006/7b226756-c221-469e-b25f-44d24523c341)

**Comment by jtlovell** [comment]
Hi there, 
This is a good idea, and one we had implemented at one point (see: https://www.frontiersin.org/articles/10.3389/fpls.2019.01144/full#f4). I dropped it from the public release, but may work to integrate it back in ... but that won't be for a while. If this is something critical to your work, we could perhaps collaborate on the code. Shoot me an email if this is of interest
