### ISSUE TITLE
ROI riparian plotting error

### ISSUE THREAD

**Issue by aamirwkhan06** [jtlovell/GENESPACE#129]
Hi John,

Thank you again for a great tool. I am using v1.3.1 for the synteny analysis of ten diverse genomes. I am trying to highlight the regions of interest. While it works well by giving a warning for fewer number of links (5):

**warning for fewer links:

Warning message:
In plot_riparian(gsParam = out, highlightBed = roi, refGenome = "Ref_genome",  :
  lines 5 in highlight bed do not connect all genomes, these may look strange in the plot**

It results in an error when I am trying to highlight regions of interest (~800; basically genes) along the genome on multiple chromosomes. Is there a limit on how many ROIs can be plotted in the riparian plot?

I am getting this error:

**Error in rbindlist(mclapply(synhitFiles, mc.cores = nCores, function(j) { :
  Item 1 of input is not a data.frame, data.table or list
Calls: plot_riparian -> rbindlist -> lapply -> FUN
Execution halted**

Kindly suggest.

Thanks!

Best regards,
Aamir

**Comment by jtlovell** [comment]
Hi there, sorry about the delay and this error. 
In systems with complex synteny, the ROI tracker can be inaccurate (see warning) ... this isn't really an algorithm thing, but instead that your region is getting fragmented into too many small or non-syntenic positions. I have been struggling with how to resolve this and do not have a good solution. Your best bet might be to plot one region at a time and see whats going on ... maybe some regions overlap in some genomes?
