### ISSUE TITLE
riparian plots based on clean_windows output

### ISSUE THREAD

**Issue by akautt** [jtlovell/GENESPACE#132]
Hi, Thanks for developing such a great tool! 

I'v been running `clean_windows` on genomic fastas and it works like a charm. The dotplots look really good, too! 

What I would really like to do is create riparian plots, though, and I'm not quite sure how to go about it. Is there an easy way to use the output from `clean_windows` as input for `plot_riparian`? It seems like there should be a way to do this without having to construct the `gsParam` object, which, based on the description...

> "Must have the following elements: blast (file.path to the original orthofinder run), synteny ( file.path to the directory where syntenic results are stored), genomeIDs ( character vector of genomeIDs)."

...and, obviously, there is no orthofinder output here, just the minimap2 alignments.

If anyone has figured this out or can point me in there right direction I'd really appreciate it! 

Thanks

**Comment by jtlovell** [comment]
Hi there - I have a function `riparian_paf` ... its not ready for primetime, but I'd be happy to share it with you. It takes a paf file and the assembly fastas and makes a riparian plot. Shoot me an email and I'll share it.
