### ISSUE TITLE
Non-syntenic ortholog is not present in pan-genome table

### ISSUE THREAD

**Issue by xiaoyezao** [jtlovell/GENESPACE#133]
Hi, I noticed that in the latest version, the non-syntenic ortholog (with tag *) is not present in pan-genome table even `showNSOrtho = TRUE` is used.

> `pangenome <- query_pangenes(gsParam,
  bed = NULL,
  refGenome = "sp21",
  transform = TRUE,
  showArrayMem = TRUE,
  showNSOrtho = TRUE,
  maxMem2Show = Inf,
  showUnPlacedPgs = TRUE
)`

Is this a planned update? 

Thank you

**Comment by jtlovell** [comment]
Thanks for the note - I haven't noticed this ... did you complete a full orthofinder run (with orthologs). If so, what version are you running?
