### ISSUE TITLE
Combining and annotating bed files w/ OGs and tandem array info fails

### ISSUE THREAD

**Issue by Jadziaa** [jtlovell/GENESPACE#136]
Dear GENESPACE team,

I am trying to replicate the plot from the GENESPACE tutorial using the test data ("human", "mouse", "platypus", "chicken", "sandLizard") on the Ubuntu 20.04.6 LTS cluster and I run into problems at the second step of the conduction GENESPACE run (Combining and annotating bed files w/ OGs and tandem array info). 

I am using  Orthofinder 2.5.5 and diamond 2.011. And The previous step calling init_genespace showed all the dependencies are valid:

Checking dependencies ...
	Found valid path to OrthoFinder v2.55: `orthofinder`
	Found valid path to DIAMOND2 v2.011: `diamond`
	Found valid MCScanX_h executable: `/home2/jadzia/tools/MCScanX/MCScanX_h`

Everything seems to working until I am getting following error:

2. Combining and annotating bed files w/ OGs and tandem array info ...
realloc(): invalid old sizerealloc(): invalid pointerrealloc(): invalid pointer
realloc(): invalid pointer
 *** caught segfault ***

 *** caught segfault ***

 *** caught segfault ***

 *** caught segfault ***
address 0x40, cause 'memory not mapped'

 *** caught segfault ***

 *** caught segfault ***

address 0x5583cbdd223c, cause 'memory not mapped'

 *** caught segfault ***

 *** caught segfault ***

 *** caught segfault ***

 *** caught segfault ***

 *** caught segfault ***

 *** caught segfault ***

 *** caught segfault ***
address 0x1b0, cause 'memory not mapped'

 *** caught segfault ***
address 0x6c, cause 'memory not mapped'

 *** caught segfault ***

 *** caught segfault ***
address 0xcc, cause 'memory not mapped'

 *** caught segfault ***
address 0xfffffffa, cause 'memory not mapped'

 *** caught segfault ***
address 0x114, cause 'memory not mapped'
Aborted (core dumped)

I would be grateful for any suggestions on how to fix this issue. 

Thank you in advance.

**Comment by jtlovell** [comment]
I am not sure ... this looks like an issue with your machine's architecture, or maybe your R installation? Perhaps try on another machine/node?
