### ISSUE TITLE
Display chromosomes with no orthologs in riparian plot

### ISSUE THREAD

**Issue by AnthonyPiot91** [jtlovell/GENESPACE#137]
Hi,

I am curious to know if it possible to plot chromosomes with no syntenic regions in the riparian plot.
As I understand, the reference genome is the only one to have all of its chromosomes displayed even if they have no orthologs in other genomes. 

I am looking to display the synteny in bacteria genomes which include many plasmids. The problem is that some of these plasmids have no orthologues with other plasmids.

Is there of way to plot these plasmids with GENESPACE nonetheless, or is there a possibility for me to tweak the code to do so?

Thanks,
Anthony

**Comment by jtlovell** [comment]
Hi Anthony - currently there is not a way to do this. But, there will be in the next release. Sorry I can't be more helpful.
