### ISSUE TITLE
Error when running init_genespace() on phytozome genomes

### ISSUE THREAD

**Issue by samseaver** [jtlovell/GENESPACE#138]
Hi, so I've got a set of Phytozome genomes on which I was able to run parse_annotations() cleanly, and so I get the corresponding bed and peptide fasta files. But when I run init_genespace, though it recognizes all the genomes, it errors out, so here's the output, and the result of the traceback() function. Unfortunately, I'm not familiar with R or the code, so I'm not sure how to follow this:

```
> gpar <- init_genespace(wd="./trial_run_2",path2mcscanx="./MCScanX")
Checking Working Directory ... PASS: `./trial_run_2`
Checking user-defined parameters ...
        Genome IDs & ploidy ...
                Athaliana_Araport11           : 1
                Atrichopoda_v1.0              : 1
                Bdistachyon_v3.1              : 1
                Brapassp_trilocularisR500_v2.1: 1
                Creinhardtii_v5.6             : 1
                CreinhardtiiCC_v6.1           : 1
                Gmax_Wm82.a4                  : 1
                Mdomestica_v1.1               : 1
                Osativa_v7.0                  : 1
                Ptrichocarpa_v4.1             : 1
                Sbicolor_v3.1.1               : 1
                Sbicolor_v5.1                 : 1
                Slycopersicum_ITAG4.0         : 1
                Smoellendorffii_v1.0          : 1
                Spolyrhiza_v2                 : 1
                Tarvense_NCBI                 : 1
                Tarvense_v1.1                 : 1
                Zmays_B73_REFERENCE           : 1
                Zmays_RefGen_V4               : 1
        Outgroup ... NONE
        n. parallel processes ... 16
        collinear block size ... 5
        collinear block search radius ... 25
        n gaps in collinear block ... 5
        synteny buffer size... 100
        only orthogroups hits as anchors ... TRUE
        n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
Error: subscript contains out-of-bounds indices
> traceback()
21: stop(wmsg(...), call. = FALSE)
20: .subscript_error("subscript contains out-of-bounds indices")
19: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,
        allow.NAs = allow.NAs)
18: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append,
        allow.NAs = allow.NAs)
17: normalizeSingleBracketSubscript(i, x, as.NSBS = TRUE)
16: .nextMethod(x = x, i = i)
15: callNextMethod()
14: .dropUnusedPoolElts(callNextMethod())
13: extractROWS(x, i)
12: extractROWS(x, i)
11: subset_along_ROWS(x, i, drop = drop)
10: fa[1:nfa]
9: fa[1:nfa]
8: paste(fa[1:nfa], collapse = "")
7: is.factor(x)
6: gsub("[^A-Za-z]", "", paste(fa[1:nfa], collapse = ""))
5: FUN(X[[i]], ...)
4: lapply(X = X, FUN = FUN, ...)
3: sapply(pepFiles, check_onlyDNA)
2: check_annotFiles(filepath = wd, genomeIDs = gids)
1: init_genespace(wd = "./trial_run_2", path2mcscanx = "./MCScanX")
```

I'm using version v1.3.1 as installed via devtools:
```> library(GENESPACE)
GENESPACE v1.3.1: synteny and orthology constrained comparative
        genomics```

**Comment by Fyasmin05** [comment]
Hi, I am having similar issue. I was able to parse the files into bed and peptide but getting following error. I would appreciate help on this. Thanks!

Checking Working Directory ... PASS: `/Genespace/workingdir`
Checking user-defined parameters ...
	Genome IDs & ploidy ... 
		Sitalica_v2.2: 1
		Sviridis_v4.1: 1
		Taestivum    : 1
		Zmays        : 1
	Outgroup ... NONE
	n. parallel processes ... 6
	collinear block size ... 5
	collinear block search radius ... 25
	n gaps in collinear block ... 5
	synteny buffer size... 100
	only orthogroups hits as anchors ... TRUE
	n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
**Error: subscript contains out-of-bounds indices**

**Comment by samseaver** [comment]
Hello, I heard from Dr Lovell independently of this posted issue, the problem was that the identifiers in the two bed and fasta files didn't match. In my case, I had to make sure I used the "translated_cds" file from the NCBI.

**Comment by LovellHAGSC** [comment]
Yeah. This is what happens when you give GENESPACE empty input files. Check the output of `parse_annotations` ... I bet something went wrong.

**Comment by Fyasmin05** [comment]
Thank you so much for both of your help. When I used genes.gff3 instead of gene_exons.gff3 it worked. However, now I am stuck at different issue which should be an easy fix. Unfortunately, I am unable to fix it. Any clue for the following warning?

Checking user-defined parameters ...
	Genome IDs & ploidy ... 
		Sitalica_v2.2: 1
		Sviridis_v4.1: 1
		Taestivum    : 1
		Zmays        : 1
	Outgroup ... NONE
	n. parallel processes ... 6
	collinear block size ... 5
	collinear block search radius ... 25
	n gaps in collinear block ... 5
	synteny buffer size... 100
	only orthogroups hits as anchors ... TRUE
	n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
	Sitalica_v2.2: 34584 / 34584 geneIDs exactly match (PASS)
	Sviridis_v4.1: 29807 / 29807 geneIDs exactly match (PASS)
	Taestivum    : 99386 / 99386 geneIDs exactly match (PASS)
	Zmays        : 39756 / 39756 geneIDs exactly match (PASS)
Checking dependencies ...
	Found valid path to OrthoFinder v2.55: `orthofinder`
	Found valid path to DIAMOND2 v2.19: `diamond`
**WARNING!!** Can't find valid path to the MCScanX_h executable in
        `/Users/zerbe/Documents/Farida/Genespace/MCScanX-master`.  Only plotting and query
        GENESPACE functions will be functional. If you want to run the main `synteny`
        function, you will need to specify a path to a valid MCScanX installation (see
        README).

**Comment by Fyasmin05** [comment]
Thank you both for your help with this. Initially, I used gene_exons_gff3 file. But when I used gene_gff3 file the files passed and did not get the earlier error. However, now I am getting the following error which ID did not match. I checked output bed and peptide file -the Gene IDs match between them. Any suggestions on this? 

Checking user-defined parameters ...
	Genome IDs & ploidy ... 
		Sitalica_v2.2: 1
		Sviridis_v4.1: 1
		Taestivum    : 1
		Zmays        : 1
	Outgroup ... NONE
	n. parallel processes ... 6
	collinear block size ... 5
	collinear block search radius ... 25
	n gaps in collinear block ... 5
	synteny buffer size... 100
	only orthogroups hits as anchors ... TRUE
	n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
	Sitalica_v2.2: 34584 / 34584 geneIDs exactly match (PASS)
	Sviridis_v4.1: 29807 / 29807 geneIDs exactly match (PASS)
	Taestivum    : 99386 / 99386 geneIDs exactly match (PASS)
	Zmays        : 39756 / 39756 geneIDs exactly match (PASS)
Checking dependencies ...
	Found valid path to OrthoFinder v2.55: `orthofinder`
	Found valid path to DIAMOND2 v2.19: `diamond`
	Found valid MCScanX_h executable: `/Users/zerbe/Downloads/MCScanX-master/MCScanX_h`
> out <- run_genespace(gpar, overwrite = T)

############################
1. Running orthofinder (or parsing existing results)
	Checking for existing orthofinder results ...
[1] FALSE
**Error in run_genespace(gpar, overwrite = T) : 
  genomes in the existing orthofinder run do not exactly match specified genomeIDs**

**Comment by Fyasmin05** [comment]
Hello again, Thank you for your help with this. I used gene.gff3 and protein.fa file. After parsing the bed file and peptide file GeneID matches. For example, I have attached a bed and peptide file to this comment. However, I am still getting an error saying the following. Could you please let me know how to fix this?

![Screen Shot 2024-03-14 at 9 43 25 AM](https://github.com/jtlovell/GENESPACE/assets/59696208/4da072c7-5f0d-42f9-b320-2d7a4dba129b)
![Screen Shot 2024-03-14 at 9 43 46 AM](https://github.com/jtlovell/GENESPACE/assets/59696208/5e08250f-8120-40f8-945a-89b2a650c3d9)


Checking user-defined parameters ...
	Genome IDs & ploidy ... 
		Sitalica : 1
		Sviridis : 1
		Taestivum: 1
		Zmays    : 1
	Outgroup ... NONE
	n. parallel processes ... 6
	collinear block size ... 5
	collinear block search radius ... 25
	n gaps in collinear block ... 5
	synteny buffer size... 100
	only orthogroups hits as anchors ... TRUE
	n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
	Sitalica : 34584 / 34584 geneIDs exactly match (PASS)
	Sviridis : 29807 / 29807 geneIDs exactly match (PASS)
	Taestivum: 99386 / 99386 geneIDs exactly match (PASS)
	Zmays    : 39756 / 39756 geneIDs exactly match (PASS)
Checking dependencies ...
	Found valid path to OrthoFinder v2.55: `orthofinder`
	Found valid path to DIAMOND2 v2.19: `diamond`
	Found valid MCScanX_h executable: `/Users/
![Screen Shot 2024-03-14 at 9 43 25 AM](https://github.com/jtlovell/GENESPACE/assets/59696208/d1f5485e-261a-4cb9-b427-f3c20ce7d2c8)
![Screen Shot 2024-03-14 at 9 43 46 AM](https://github.com/jtlovell/GENESPACE/assets/59696208/ca792d0f-54fa-4163-8661-c6d37dee6cbc)
Downloads/MCScanX-master/MCScanX_h`
> out <- run_genespace(gpar, overwrite = T)

############################
1. Running orthofinder (or parsing existing results)
	Checking for existing orthofinder results ...
[1] FALSE
**Error in run_genespace(gpar, overwrite = T) : 
  genomes in the existing orthofinder run do not exactly match specified genomeIDs**

**Comment by jtlovell** [comment]
Try removing the /orthofinder subdirectory (in your genespace working directory) and re-running.

**Comment by aberaslop** [comment]
Hi! Thank you so much for the great tool!

I am also encountering this same error. I have tried your suggestion of deleting the /orthofinder subdirectory and re-running, but I get the same error. Here are the names of the genomes in the different files:

peptide files:
>FSPLA_000001
>FSPLA_000002

gff3 files:

##gff-version 3
contig_1        funannotate     gene    27840   30090   .       -       .       ID=FSPLA_000001;
contig_1        funannotate     mRNA    27840   30090   .       -       .       ID=FSPLA_000001-T1;Parent=$
contig_1        funannotate     exon    29654   30090   .       -       .       ID=FSPLA_000001-T1.exon1;P$
contig_1        funannotate     exon    28950   29605   .       -       .       ID=FSPLA_000001-T1.exon2;P$
contig_1        funannotate     exon    27840   28648   .       -       .       ID=FSPLA_000001-T1.exon3;P$

resulting bed:
contig_1        27839   30090   FSPLA_000001
contig_1        31946   33257   FSPLA_000002
contig_1        33748   34831   FSPLA_000003
contig_1        35794   36862   FSPLA_000004
contig_1        39674   40265   FSPLA_000005
contig_1        41884   43505   FSPLA_000006

This is what I ran:

gids <- c("FSPIC","FENIG","FSPLA","FCALT")

#parse annotations
parsedPaths<-parse_annotations(
  genomeDirs = gids,
  gffIdColumn = "ID",
  gffStripText = "ID=", 
  headerEntryIndex = 1,
  headerSep = " ",  
  headerStripText = "ID=",
  genespaceWd = runwd,
  rawGenomeRepo = "~/Documents/genespace/rawGenomes")

gpar <- init_genespace(
  genomeIDs = gids, 
  speciesIDs = gids, 
  versionIDs = gids, 
  ploidy = rep(1,4), 
  wd = runwd, 
  gffString = "gff", 
  pepString = "fa", 
  path2orthofinder = "/miniconda3/envs/genespace/bin/orthofinder", 
  path2mcscanx = "~/Documents/MCScanX-1.0.0/",
  rawOrthofinderDir="~/Documents/genespace/orthofinder/",
  rawGenomeDir = file.path(runwd, "rawGenomes"))

#run
out <- run_genespace(gpar, overwrite = T)



This runs orthofinder and stops immediately after (I have also tried to run it withy an orthofinder run outside of genespace, to no avail). When I run it again to proceed forward, it notes:


############################
1. Running orthofinder (or parsing existing results)
	Checking for existing orthofinder results ...
[1] FALSE
Error in run_genespace(gpar, overwrite = T) : 
  genomes in the existing orthofinder run do not exactly match specified genomeIDs 


Any help is appreciated! Thanks a lot!
L.
