### ISSUE TITLE
run orthofinder outside genespace

### ISSUE THREAD

**Issue by xiaoyezao** [jtlovell/GENESPACE#14]
Hi John,

Is it possible to run orthofinder independently, and then reuse the orthofinder results in genespace?

Thank you,

Tao

**Comment by jtlovell** [comment]
Hi Tao, 
Yes and no - if you ran orthofinder using the genespace-formatted annotations, then totally. It should be explained in the `init_genespace()` and `run_orthofinder()` call if orthofinder isn't in the path. Alternatively, you can set the gsParam list to point to the existing orthofinder directory via `gpar$paths$orthofinder <- "path/to/your/existingRun"`. 
However, if you ran it on un-formatted annotations, it will take a bit more work. You'll need to make a dictionary of the genespace geneIDs (which are made using `parse_annotations()` etc.) and the ids in the original orthofinder run in orthofinderDir/runDate/workingDirectory/sequenceIDs.txt and replace the old names with the new ones. I can help with this if needed. 
Although, honestly, it probably is easier to just re-run orthofinder using the genespace IDs, unless the run was huge. 
Hope this helps, 
John

**Comment by jtlovell** [comment]
No prob. 

Your best bet is to convert the bed to gff3 - this can be done in a variety of ways, including natively in Rtracklayer (import/export). Then read it in the way you would normally with `parse_annotations`. There are other ways to coerce the data into GENESPACE format, but this will be by far the easiest way. If you do the conversion manually just make sure you switch the indexing from 0 to 1 following gff3 specs.

**Comment by xiaoyezao** [comment]
Sorry to open this issue again.

I ran orthofinder outside genespace, and would feed the results to genespace. I understand that pointing `OrthoFinder/Results_May04/` to genespace is fine, but I am wondering which part of the orthofinder results is used by genespace? Is it `OrthoFinder/Results_May04/Orthogroups/Orthogroups.tsv` ?

**Comment by xiaoguizz** [comment]
> Hi Tao, Yes and no - if you ran orthofinder using the genespace-formatted annotations, then totally. It should be explained in the `init_genespace()` and `run_orthofinder()` call if orthofinder isn't in the path. Alternatively, you can set the gsParam list to point to the existing orthofinder directory via `gpar$paths$orthofinder <- "path/to/your/existingRun"`. However, if you ran it on un-formatted annotations, it will take a bit more work. You'll need to make a dictionary of the genespace geneIDs (which are made using `parse_annotations()` etc.) and the ids in the original orthofinder run in orthofinderDir/runDate/workingDirectory/sequenceIDs.txt and replace the old names with the new ones. I can help with this if needed. Although, honestly, it probably is easier to just re-run orthofinder using the genespace IDs, unless the run was huge. Hope this helps, John

Hello,
 I'm having the same issue, but when I specify an already existing orthofinder result with rawOrthofinderDir in init_genespace(), genescape doesn't detect my orthofinder file.
Thank you very much for your prompt reply,
Zhou
