### ISSUE TITLE
clean_windows docs?

### ISSUE THREAD

**Issue by tallnuttrbgv** [jtlovell/GENESPACE#141]
Hi,

latest version is 1.4 but docs say since 1.3 it has the function 'clean_windows' for annotation free running. Are there any docs on how to use this? I cannot see it mentioned in the tutorial.

Thanks,

Theo

**Comment by jtlovell** [comment]
Hi Theo ... sorry for the delay here. We are planning on releasing a new package with this functionality this summer. clean_windows will stay hidden in GENESPACE until v1.5, then dropped.
