### ISSUE TITLE
Synteny / homoeologs in polyploids

### ISSUE THREAD

**Issue by tallnuttrbgv** [jtlovell/GENESPACE#144]
Hi,

unfortunately I could not work out how to do this from the docs and after several attempts need to ask for help.

I have a genome that is a putative triploid. BUSCOs on the purged assembly are 55% duplicated and the species is known to form triploids. I wanted to use gs to identify homoeolog contigs (the assembly is hifiasm and mostly complete chromosomes). When I ran gs on the assembly to itself the riparian plot only showed single syntenitc groups. I set onlyOgAnchors=F, and nSecondHits=3. What is your recommended method to do this?

Thanks.

![image](https://github.com/jtlovell/GENESPACE/assets/98720470/847eebda-5646-43fb-86d2-89c51b6a25bb)

**Comment by jtlovell** [comment]
Sorry about the slow response ... were you able to resolve this? We go into detail about how to handle genomes w/ WGDs in the paper. In short, use an outgroup that predates the WGD.

**Comment by tallnuttrbgv** [comment]
Hi,

I don't think that will achieve the plot I was after - I need to see more than one syntenic hit. The current plots only show the best one (I assume). I have started using other methods now (pairwise dotplots) but it would still be nice to be able to show a riparian plot. Another option is perhaps circos, but it is rather difficult to use.

Thanks.

**Comment by jtlovell** [comment]
The problem isn't plotting, but your definition of orthology. Without an outgroup, you'll never see the WGD from orthogroups.
