### ISSUE TITLE
error in run_genespace

### ISSUE THREAD

**Issue by jdobry-lab** [jtlovell/GENESPACE#146]
I get the following error during Generating dot plots for all hits. However most or all of the dotplots are generated in the wd:

Error in seq.default(from = 1000, to = max(hc$rnd1), by = 1000) : 
  'to' must be a finite number

**Comment by jtlovell** [comment]
not sure ... are you working with very small genomes?

**Comment by jdobry-lab** [comment]
Thank you for getting back to me. Initially, I generated this analysis on version 0.9.3 over a year ago and was trying to recreate this with the latest version. I used a scaffold from a large inversion on one chromosome and compared it to several full genomes.
