### ISSUE TITLE
riparian plots are inconsistent

### ISSUE THREAD

**Issue by gorliver** [jtlovell/GENESPACE#149]
Thank you for the tool!
I have successfully run GENESPACE using ten genomes, and the riparian plot looks nice. Here's a screenshot with two genomes.
![image](https://github.com/jtlovell/GENESPACE/assets/15271446/e64a485f-e2b3-4f39-a6a0-5243afe100b3)

However, if I plot a new riparian plot of just the two genomes, use the following command:
```
ripd <- plot_riparian(gsParam = out,genomeIDs=new2run[c(13,14)],refGenome = "tomato", useRegions = FALSE,useOrder=FALSE)
```
The riparian plot looks very different:
![image](https://github.com/jtlovell/GENESPACE/assets/15271446/c49101f1-579a-432a-be7a-3ff34c498dbb)

Several blocks were missed in the new riparian plot. Did I need to include anything in the parameters?

**Comment by jtlovell** [comment]
I think you are using regions on the top and blocks on the bottom. regions average across positions that may lack alignments (e.g. pericentromers on chr01)

**Comment by gorliver** [comment]
I see. Many thanks!
