### ISSUE TITLE
BUG when specifying rawOrthofinderDir

### ISSUE THREAD

**Issue by dmacguigan** [jtlovell/GENESPACE#157]
Hello,

I am attempting to use previously generated OrthoFinder results with GENESPACE. However, I noticed that line 84 of [run_genespace.R](https://github.com/jtlovell/GENESPACE/blob/4c9902acd9b901e9482ba05eafe86db50750eca8/R/run_genespace.R#L84) does the following:

```
gsParam$paths$rawOrthofinder <- gsParam$paths$orthofinder
```

This means that no matter what the user specifies for the `rawOrthofinderDir` option when running `init_genespace`, the `run_genespace` function will always use the default OrthoFinder results directory (`file.path(wd, "orthofinder")`). 

Once I matched the expected directory structure (copied my prior OrthoFinder run into "wd/orthofinder"), the `run_genespace` function proceeds correctly and does not attempt to rerun OrthoFinder.

**Comment by jtlovell** [comment]
Thanks! Appreciate this report, and have added it to my notes.
