### ISSUE TITLE
How to Change Chromosome Shapes or Display Centromeres?

### ISSUE THREAD

**Issue by YYsama11** [jtlovell/GENESPACE#159]
Hi,

Thank you for developing such a useful tool, GENESPACE. I have a couple of questions:

Is there a way to change the shapes of chromosomes?
Is it possible to display centromeres in the plots?
I have thoroughly reviewed the entire manual, but I could not find any information on drawing centromeres. Did I miss something, or is this feature currently not available in GENESPACE?

Any guidance or information on this would be greatly appreciated.

Thank you!

Best regards,

**Comment by jtlovell** [comment]
Hi there. 
Shapes, yes `howSquare` can go from rectangular to oval. 
Centromeres, no. Since they are not related to gene-space, they really don't fit into this. However, this is something that will be available in my next package, DEEPSPACE, which will come out in beta this summer. 
JL
