### ISSUE TITLE
HOG path not getting set?

### ISSUE THREAD

**Issue by hyphaltip** [jtlovell/GENESPACE#163]
orthofinder completes successfully but the search for the files seems to be failing 

I've been able to run genespace successfully for a while but had to install new package with a new R upgrade and now I am getting this failure:

```
Error in if (is.na(gsParam$synteny$hogs)) { : argument is of length zero
```

I don't see where you set the subfolders for these only that `resultsDir` is used in the `set_syntenyParams.R` so not sure if it just isn't traversing the subfolders or if something else is wrong.

Running: ` OrthoFinder version 2.5.5`  and `GENESPACE v1.3.1`

**Comment by jtlovell** [comment]
OK - Thanks for this ... I haven't check forward compatibility to the newer R versions. Thats something I'm planning for next month. But, I wonder what would cause this. ... this errors out right at the beginning of the GENESPACE run, eh?

**Comment by hyphaltip** [comment]
Yeah right at the beginning, this R 4.3.0 - I'll just go back to an older R if that is the solution

**Comment by hyphaltip** [comment]
Okay I think the issues was a leftover 'results' folder!
