### ISSUE TITLE
Running OrthoFinder and MCScanX Outside of GENESPACE

### ISSUE THREAD

**Issue by jessiepelosi** [jtlovell/GENESPACE#165]
Hi there, 

Is it possible (or perhaps possible in the future) to run OrthoFinder and MCScanX outside of GENESPACE and then feed the resulting outfiles to GENESPACE? I'm having issues with installing all of these on the same computer, and it would be much easier to run OrthoFinder and MCScanX on a cluster and then input the resulting files into a local machine in R.

Thanks!
Jessie

**Comment by jtlovell** [comment]
You can definitely run OrthoFinder outside ... If you don't have a valid install just initialize the run and run it as you would normally, then GENESPACE will print the orthofinder command and make the directory to run it out of. 

MCScanX *should be easy to install on any platfrom. Sry you cant get it going. But GENESPACE uses MCScanX internally, so you can't call it outside and pipe the results in.

**Comment by jessiepelosi** [comment]
Thanks - this worked perfectly!
