### ISSUE TITLE
Error in step 7 of run_genespace

### ISSUE THREAD

**Issue by brennandmcdonald** [jtlovell/GENESPACE#169]
Hello. All steps of run_genespace ran correctly until step 7, where I got the following error output:

> 7. Final block coordinate calculation and riparian plotting ...
> 	##############
> 	Calculating syntenic blocks by reference chromosomes ... 
> 		n regions (aggregated by 25 gene radius): 14254
> 		n blocks (collinear sets of > 5 genes): 19246
> 	##############
> 	Building ref.-phased blks and riparian plots for haploid genomes:
> 		A_comosus     : 17107 phased blocks
> Error in rbindlist(mclapply(synhitFiles, mc.cores = nCores, function(j) { : 
>   Item 8 of input is not a data.frame, data.table or list
> Calls: run_genespace -> plot_riparian -> phase_blks -> rbindlist

What steps can I take to address this issue?

Thank you.

**Comment by Kendall-Lee** [comment]
Hi did you ever fix this issue?
