### ISSUE TITLE
GENESPACE can't find the validation path for orthofinder

### ISSUE THREAD

**Issue by Luxet** [jtlovell/GENESPACE#172]
Hello,

I have installed orthofinder by using conda, and it was fine when i run "orthofinder -h" in the shell. Besides, I also tried to use `system("orthofinder -h")` in the R, it worked fine. After used sys.getenv(), the bin folder (including the orthofinder executive file) was also in the PATH of R.
I have checked my shell PATH, which also already included the path for orthofinder.

However, in GENESPACE, when I tried to run_orthofinder(gpar), it says can't find valid path for orthofinder.
I could run the orthofinder in shell seperately, but I need the parameter "ploidy=2". When I used the existing orthofinder folder to continue the running, error occured at step 5
```
Error in rbindlist(mclapply(names(spl01), mc.cores = nCores, function(j) { :
  Item 1 of input is not a data.frame, data.table or list
```

What could be going wrong?

Thank you for your time,
Best
-Jessie

**Comment by LovellHAGSC** [comment]
I'm not sure ... if it can't find orthofinder, it should error out at the `init_genespace` step, not during `run_genespace`. To diagnose the error you report here, switch `nCores` to 1 and rerun ... it should give a more informative message.

**Comment by Luxet** [comment]
> I'm not sure ... if it can't find orthofinder, it should error out at the `init_genespace` step, not during `run_genespace`. To diagnose the error you report here, switch `nCores` to 1 and rerun ... it should give a more informative message.

Thanks for your reply! Here is my error when i used nCores = 1 in `init_genespace` step.

```
        Genome IDs & ploidy ...
                sp1: 2
                sp2: 2
                sp3: 2
                sp4: 2
        Outgroup ... NONE
        n. parallel processes ... 1
        collinear block size ... 5
        collinear block search radius ... 25
        n gaps in collinear block ... 5
        synteny buffer size... 100
        only orthogroups hits as anchors ... TRUE
        n secondary hits ... 0
        only orthogroup hits for homeolog block anchors ... FALSE
Checking annotation files (.bed and peptide .fa):
        sp1: 46935 / 46935 geneIDs exactly match (PASS)
        sp2: 56675 / 56675 geneIDs exactly match (PASS)
        sp3: 41259 / 41259 geneIDs exactly match (PASS)
        sp4: 54533 / 54533 geneIDs exactly match (PASS)
Checking dependencies ...
      **WARNING!!**, orthofinderInBlk was set to TRUE; however, this
      routine requires a valid path to the OrthoFinder program to be
      specified within R. Therefore, orthofinderInBlk has been set to
      FALSE. If this is not desired, please re-run build_params with a
      valid path2orthofinder.
        Found valid path to DIAMOND2 v2.11: `diamond`
        Found valid MCScanX_h executable: `/home/luoliying/Software/MCScanX-master/MCScanX_h`
Warning message:
In get_orthofinderVersion(path2orthofinder) : NAs introduced by coercion
```

I also tried to specify the orthofinder path in the parameter by using `path2orthofinder = "/home/Jes/software/bin/"`. However, the error was still the same.
Thanks for your time,
Best
-Jessie

**Comment by LovellHAGSC** [comment]
I have no idea, unless you are using a deprecated version of Orthofinder (<2.5.2) ... `init_genespace` calls `GENESPACE::get_orthofinderVersion`, which checks if the path you provide can be called to get a help file. 

Please confirm this ...

If `p2of <- "path/to/orthofinder"` (however you would call orthofinder from your terminal)
1. `system2(p2of, "-h", stdout = TRUE)` gives the full help file for orthofinder, and orthofinder version >=2.5.2
2. `GENESPACE::get_orthofinderVersion(p2of)` returns NA

If both 1 and 2, then I am dumbfounded ... `GENESPACE::get_orthofinderVersion` just calls `system2(path, "-h", stdout = TRUE)` where `path` is the supplied path to orthofinder

John

**Comment by Luxet** [comment]
> I have no idea, unless you are using a deprecated version of Orthofinder (<2.5.2) ... `init_genespace` calls `GENESPACE::get_orthofinderVersion`, which checks if the path you provide can be called to get a help file.
> 
> Please confirm this ...
> 
> If `p2of <- "path/to/orthofinder"` (however you would call orthofinder from your terminal)
> 
> 1. `system2(p2of, "-h", stdout = TRUE)` gives the full help file for orthofinder, and orthofinder version >=2.5.2
> 2. `GENESPACE::get_orthofinderVersion(p2of)` returns NA
> 
> If both 1 and 2, then I am dumbfounded ... `GENESPACE::get_orthofinderVersion` just calls `system2(path, "-h", stdout = TRUE)` where `path` is the supplied path to orthofinder
> 
> John

Thank you for your reply! I have tried both your suggestions, and 1 and 2 both happened.
1. When I used `system2(p2of, "-h", stdout = TRUE)`, it does give the full help file for orthofinder, and the orthofinder version were "3.0.1b1"
2. `GENESPACE::get_orthofinderVersion(p2of)` also returns NA
```
> GENESPACE::get_orthofinderVersion(path2orthofinder)
[1] NA
Warning message:
In GENESPACE::get_orthofinderVersion(path2orthofinder) :
  NAs introduced by coercion
```
My R version is 4.4.1 in centos7 and orthofinder version is 3.0.1b1. 
And I also tried to use the R v4.1.2, but the error was the same.
I'm also very confused about this strange situation, which orthofinder can be normally arosed by R and it's normal in the shell, but can't be identified by get_orthofinderVersion. 

Thanks for your time,
Best
-Jessie

**Comment by jtlovell** [comment]
OK. so this is how I find out about a new orthofinder release, eh? 
Good news is this is an easy fix. Bad news is you'll need to re-do your orthofinder run with v2.5x (can be installed using conda specifying the version). 

The alternative is to wait for me to write a patch to use the apparently modified output from v3.x orthofinder. 

I'll write a patch to the error checking so that it catches v3 orthofinder and push that tonight along with an update to the readme to specify orthofinder version in the conda install. 

Thanks for sticking with this!
John
