### ISSUE TITLE
Load previously generated genespace files instead of re-running everything?

### ISSUE THREAD

**Issue by Snodgras** [jtlovell/GENESPACE#175]
Hello!

I was wondering if there was any way to load in previously generated genespace runs from the result files instead of re-running the entire analysis from the start. So if you're working in a blank workspace where a previous genespace object no longer exists, but all the result files have been generated, could you load in those result files as a genespace object?

I ask because my R sessions keep crashing and then I lose the genespace object from my work environment, but I have the results files saved. It would save me a lot of time if I could read in a previously generated genespace object rather than re-running genespace over and over again. 

Thanks for your time and patience,
Sam

**Comment by jtlovell** [comment]
Yup! Just set `gs <- init_genespace(..., wd = "path/to/previous/run")` and it should find everything it needs. Depending on where your previous crashed out, you might need to run `newgs <- run_genespace(gs, overwrite = FALSE)` to get all the paths in order.

**Comment by Snodgras** [comment]
Thank you so much!
