### ISSUE TITLE
Question about result of human_pangenomeDB.txt.gz

### ISSUE THREAD

**Issue by zhangzhiyangcs** [jtlovell/GENESPACE#20]
Hi,
    Thanks for your wonderful tools. I have some question about below result. Why the same LOC114676391 gene have different og ID? Should I filter one? My attention is get a sets of colinearity gene pairs from multi-genome assemblies.  Should I select gene pairs that isSynOgOnly is TRUE? or you have better suggestion.
Thanks a lot.
Zhiyang Zhang
############ human_pangenomeDB.txt.gz
pgChr   pgOrd   pgID    og      ofID    isRep   genome  isDirectSyn     isSynOgOnly     isArrayRep      isNSOrtho       id
3      65.5              69    39    0_69    TRUE   chimp   FALSE        FALSE        TRUE        FALSE      LOC107970568
3      65.5              70    230   2_866   TRUE   rhesus  FALSE        FALSE        TRUE        FALSE      LOC114676395
3      65.5              70    230   2_891   TRUE   rhesus  FALSE        FALSE        FALSE       FALSE      LOC703060
3      65.5              69    39    2_837   FALSE  rhesus  FALSE        FALSE        TRUE        FALSE      LOC114676391
3      65.5              69    225   2_837   FALSE  rhesus  FALSE        FALSE        TRUE        FALSE      LOC114676391

**Comment by zhangzhiyangcs** [comment]
Hi, John
Thanks your advice. If I have nearly 60 assemblies, and I want get to the gene sets which conform to orthogroup and synteny across 60 assemblies.  Should I extract the gene sets from *pangenomeDB.txt.gz file?

**Comment by jtlovell** [comment]
The presence of one gene in three `og` levels is concerning (230, 225, 39). I'll look into this and get back to you. It should not happen, except in rare conditions that should not be present in the example data (segmental duplicates, very very large tandem arrays, etc.).
