### ISSUE TITLE
Error in x$gen1 : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by alexvasilikop** [jtlovell/GENESPACE#21]
Hello, 
after running orthofinder within Genespace-R I used the following comand to infer the synteny
bu I get an error (see below). What could be the issue?

$gpar <- synteny(gsParam = gpar)

########
Indexing location of orthofinder results ... Done!
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 33555 global OGs for 124547 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		Adinetaricciae: 11/0, 33209/0, 28644/0
		Adinetasp: 9/0, 39072/0, 31502/0
		Adinetavaga: 6/0, 31335/0, 28073/0
		Brachionuscalyciflorus: 12/0, 20931/0, 14732/0
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
		Adinetaricciae: 4294 genes in 1876 collinear arrays
		Adinetasp: 6649 genes in 2923 collinear arrays
		Adinetavaga: 2820 genes in 1295 collinear arrays
		Brachionuscalyciflorus: 6967 genes in 2387 collinear arrays
Pulling synteny for 10 unique pairwise combinations of genomes
	Running 2 chunks of up to 6 combinations each:
	Chunk 1 / 2 (16:50:15) ... Done!
	Adinetas-Adinetar: 524897 (tot), 33419/12 (reg), 20346/74 (blk)
	Adinetas-Adinetav: 506457 (tot), 34134/8 (reg), 21247/39 (blk)
	Adinetar-Adinetav: 419189 (tot), 31785/10 (reg), 20493/90 (blk)
Error in x$gen1 : $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(1:nrow(splSynp[[i]]), mc.cores = nCores, function(j) { :
  scheduled cores 4, 5, 6 encountered errors in user code, all values of the jobs will be affected

**Comment by jtlovell** [comment]
My guess is that two of the genomes have no identifiable synteny. You can check if this is right by setting the synteny params with much more relaxed settings. For example, 
```
gpar <- set_syntenyParams(gpar, onlyOgAnchors = FALSE, blkSize = 2, nGaps = 20)
gpar <- synteny(gpar)
```
This is an error catch that will be part of the next release. 

If the error persists, rerun with the following and post the error here.
```
gpar$params$nCores <- 1
gpar <- synteny(gpar)
```
Setting to a single core will give more informative errors, since the code isn't buried in parallel.

Let me know if this helps, 
John

**Comment by alexvasilikop** [comment]
Hello again,

Thanks for the prompt reply. So another problem I forgot to mention is that in the dataset there are 5 genomes (there is one used as outgroup in orthofinder). But the synteny analysis log above only outputs 4 of them. What is the reason for this?

I rerun the whole analysis using your suggestions (see output below) so maybe you are right it seems a pair of genomes does not show but does not say which genomes do not share synteny (maybe some addition to consider). i guess for the ones that that are printed on the screen there is some synteny identified?
 
##############################################################"
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 33555 global OGs for 124547 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		Adinetaricciae: 11/0, 33209/0, 28644/0
		Adinetasp: 9/0, 39072/0, 31502/0
		Adinetavaga: 6/0, 31335/0, 28073/0
		Brachionuscalyciflorus: 12/0, 20931/0, 14732/0
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
		Adinetaricciae: 4294 genes in 1876 collinear arrays
		Adinetasp: 6649 genes in 2923 collinear arrays
		Adinetavaga: 2820 genes in 1295 collinear arrays
		Brachionuscalyciflorus: 6967 genes in 2387 collinear arrays
Pulling synteny for 10 unique pairwise combinations of genomes
	Running 10 chunks of up to 1 combinations each:
	Chunk 1 / 10 (11:05:09) ... Done!
	Adinetas-Adinetar: 524897 (tot), 34837/18 (reg), 22379/1979 (blk)
	Chunk 2 / 10 (11:06:09) ... Done!
	Adinetas-Adinetav: 506457 (tot), 34770/9 (reg), 23368/874 (blk)
	Chunk 3 / 10 (11:06:54) ... Done!
	Adinetar-Adinetav: 419189 (tot), 32544/11 (reg), 21405/1572 (blk)
	Chunk 4 / 10 (11:07:43) ... Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  NA vs. NA does not have any detectable synteny ...
            either relax synteny parameters or drop one of these genomes
#########################################################################################



Then I relaxed the nGaps parameter even more and restarted  but I get another error about plotting limits..:
$gpar <- set_syntenyParams(gpar, onlyOgAnchors = FALSE, blkSize = 2, nGaps = 40)
$gpar <- synteny(gsParam = gpar)



########################################################################
Indexing location of orthofinder results ... Done!
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 33555 global OGs for 124547 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		Adinetaricciae: 11/0, 33209/0, 28644/0
		Adinetasp: 9/0, 39072/0, 31502/0
		Adinetavaga: 6/0, 31335/0, 28073/0
		Brachionuscalyciflorus: 12/0, 20931/0, 14732/0
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
		Adinetaricciae: 4294 genes in 1876 collinear arrays
		Adinetasp: 6649 genes in 2923 collinear arrays
		Adinetavaga: 2820 genes in 1295 collinear arrays
		Brachionuscalyciflorus: 6967 genes in 2387 collinear arrays
Pulling synteny for 7 unique pairwise combinations of genomes
	Running 7 chunks of up to 1 combinations each:
	Chunk 1 / 7 (11:26:38) ... Done!
	Adinetas-Brachion: 159146 (tot), 891/16 (reg), 195/115 (blk)
	Chunk 2 / 7 (11:26:46) ... Error in plot.window(...) : need finite 'xlim' values
In addition: There were 19 warnings (use warnings() to see them)
.
.
$warnings()
Warning messages:
1: In max(structure(integer(0), dim = c(0L, 2L), dimnames = list( ... :
  no non-missing arguments to max; returning -Inf
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
4: In min(x) : no non-missing arguments to min; returning Inf
5: In max(x) : no non-missing arguments to max; returning -Inf
6: In min(y) : no non-missing arguments to min; returning Inf
7: In max(y) : no non-missing arguments to max; returning -Inf
8: In min(x) : no non-missing arguments to min; returning Inf
9: In max(x) : no non-missing arguments to max; returning -Inf
10: In min(n) : no non-missing arguments to min; returning Inf
11: In max(n) : no non-missing arguments to max; returning -Inf
12: In min(tp$x) : no non-missing arguments to min; returning Inf
13: In min(x) : no non-missing arguments to min; returning Inf
14: In max(x) : no non-missing arguments to max; returning -Inf
15: In min(tp$y) : no non-missing arguments to min; returning Inf
16: In min(x) : no non-missing arguments to min; returning Inf
17: In max(x) : no non-missing arguments to max; returning -Inf
18: In max(tp$x) : no non-missing arguments to max; returning -Inf
19: In max(tp$y) : no non-missing arguments to max; returning -Inf

###################################################################################

But somehow this is a bit strange to me I guess it depends on the definition of synteny but I would expect some synteny (groups of genes on the same chromosomes between species) between these genomes even if the order (i.e. collinearity of blocks) is not strictly constrained. 

This is especially given that you identify some synteny among vertebrate genomes in your biorxiv article https://www.biorxiv.org/content/10.1101/2022.03.09.483468v1. What parameters did you use to make the riparian plot for vertebrates in fig. 1 of your biorxiv preprint?

It could be that fewer anchors (ancestral linkage groups) need to be specified e.g. see this paper (https://www.science.org/doi/10.1126/sciadv.abi5884). Any ideas on how to implement this?

Many thanks for the feedback

**Comment by alexvasilikop** [comment]
Ok short update:
Using:
$gpar <- set_syntenyParams(gpar, onlyOgAnchors = TRUE, blkSize = 2, nGaps = 60)

Terminates normally but then I have a problem rendering the plot (Also there is one species missing in the comparisons (the outgroup of orthofinder, see previous message 5 species and not 4 in total):
################################################
#Parsing the gff files ... 
# Reading the gffs and adding orthofinder IDs ... Done!
# Found 33555 global OGs for 124547 genes
# QC-ing genome to ensure chromosomes/scaffolds are big enough...
#         Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
#   Adinetaricciae: 11/0, 33209/0, 28644/0
#   Adinetasp: 9/0, 39072/0, 31502/0
#   Adinetavaga: 6/0, 31335/0, 28073/0
#   Brachionuscalyciflorus: 12/0, 20931/0, 14732/0
# All look good!
# Defining collinear orthogroup arrays ... 
# Found the following counts of arrays / genome:
#   Adinetaricciae: 4294 genes in 1876 collinear arrays
#   Adinetasp: 6649 genes in 2923 collinear arrays
#   Adinetavaga: 2820 genes in 1295 collinear arrays
#   Brachionuscalyciflorus: 6967 genes in 2387 collinear arrays
#Pulling synteny for 10 unique pairwise combinations of genomes
# Running 10 chunks of up to 1 combinations each:
# Chunk 1 / 10 (11:55:03) ... Done!
# Adinetas-Adinetar: 524897 (tot), 50105/46 (reg), 24356/1896 (blk)
# Chunk 2 / 10 (11:56:27) ... Done!
# Adinetas-Adinetav: 506457 (tot), 52676/42 (reg), 25446/2619 (blk)
# Chunk 3 / 10 (11:57:53) ... Done!
# Adinetar-Adinetav: 419189 (tot), 44323/35 (reg), 22888/2336 (blk)
# Chunk 4 / 10 (11:59:19) ... Done!
# Adinetas-Brachion: 159146 (tot), 5169/52 (reg), 849/542 (blk)
# Chunk 5 / 10 (11:59:35) ... Done!
# Adinetar-Brachion: 152947 (tot), 5949/60 (reg), 955/630 (blk)
# Chunk 6 / 10 (11:59:53) ... Done!
# Adinetav-Brachion: 149259 (tot), 5118/55 (reg), 828/532 (blk)
# Chunk 7 / 10 (12:00:07) ... Done!
# Adinetas-Adinetas: 608255 (tot), 53925/9 (reg), 39055/9 (blk)
# Chunk 8 / 10 (12:00:28) ... Done!
# Adinetar-Adinetar: 453528 (tot), 46260/11 (reg), 33194/11 (blk)
# Chunk 9 / 10 (12:00:42) ... Done!
# Adinetav-Adinetav: 403019 (tot), 40889/6 (reg), 31327/6 (blk)
# Chunk 10 / 10 (12:00:54) ... Done!
# Brachion-Brachion: 244440 (tot), 47038/12 (reg), 20916/12 (blk)
#Defining synteny-constrained orthogroups ... 
# Found 63712 synteny-split OGs for 124547 genes
#Found 63712 OGs across 124547 genes. gff3-like text file written to:
# ~/Documents/genespace//results/gffWithOgs.txt.gz
#Calculating syntenic block breakpoints ... 
# Found 17148 blocks. Text file written to:
# ~/Documents/genespace//results/syntenicBlocks.txt.gz:
###########################################################

$plot_riparianHits(gsParam = gpar)
#  Reading hits ... Done!
#  Generating plot coordinates ... Done!
#  Rendering plot ... Done!

But then the plot is not rendered (I am running this from the command line using R and not with Rstudio).

**Comment by alexvasilikop** [comment]
Hello,

short update, running with even more relaxed synteny criteria but still constrained orthogroups gives no error (but still there is one species missing from the comparisons (the outgroups in the orthofinder analysis, see my message above -> is this normal?):

> gpar <- set_syntenyParams(gpar, onlyOgAnchors = TRUE, blkSize = 2, nGaps = 60)
> gpar <- synteny(gsParam = gpar)

####################################################################"
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 33555 global OGs for 124547 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		Adinetaricciae: 11/0, 33209/0, 28644/0
		Adinetasp: 9/0, 39072/0, 31502/0
		Adinetavaga: 6/0, 31335/0, 28073/0
		Brachionuscalyciflorus: 12/0, 20931/0, 14732/0
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
		Adinetaricciae: 4294 genes in 1876 collinear arrays
		Adinetasp: 6649 genes in 2923 collinear arrays
		Adinetavaga: 2820 genes in 1295 collinear arrays
		Brachionuscalyciflorus: 6967 genes in 2387 collinear arrays
Pulling synteny for 10 unique pairwise combinations of genomes
	Running 10 chunks of up to 1 combinations each:
	Chunk 1 / 10 (11:50:03) ... Done!
	Adinetas-Adinetar: 524897 (tot), 41131/41 (reg), 24068/569 (blk)
	Chunk 2 / 10 (11:51:14) ... Done!
	Adinetas-Adinetav: 506457 (tot), 42144/36 (reg), 25188/518 (blk)
	Chunk 3 / 10 (11:52:23) ... Done!
	Adinetar-Adinetav: 419189 (tot), 36530/27 (reg), 23122/521 (blk)
	Chunk 4 / 10 (11:53:31) ... Error in plot.window(...) : need finite 'xlim' values
In addition: There were 19 warnings (use warnings() to see them)
> gpar <- set_syntenyParams(gpar, onlyOgAnchors = TRUE, blkSize = 2, nGaps = 60)
> gpar <- synteny(gsParam = gpar)
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 33555 global OGs for 124547 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		Adinetaricciae: 11/0, 33209/0, 28644/0
		Adinetasp: 9/0, 39072/0, 31502/0
		Adinetavaga: 6/0, 31335/0, 28073/0
		Brachionuscalyciflorus: 12/0, 20931/0, 14732/0
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
		Adinetaricciae: 4294 genes in 1876 collinear arrays
		Adinetasp: 6649 genes in 2923 collinear arrays
		Adinetavaga: 2820 genes in 1295 collinear arrays
		Brachionuscalyciflorus: 6967 genes in 2387 collinear arrays
Pulling synteny for 10 unique pairwise combinations of genomes
	Running 10 chunks of up to 1 combinations each:
	Chunk 1 / 10 (11:55:03) ... Done!
	Adinetas-Adinetar: 524897 (tot), 50105/46 (reg), 24356/1896 (blk)
	Chunk 2 / 10 (11:56:27) ... Done!
	Adinetas-Adinetav: 506457 (tot), 52676/42 (reg), 25446/2619 (blk)
	Chunk 3 / 10 (11:57:53) ... Done!
	Adinetar-Adinetav: 419189 (tot), 44323/35 (reg), 22888/2336 (blk)
	Chunk 4 / 10 (11:59:19) ... Done!
	Adinetas-Brachion: 159146 (tot), 5169/52 (reg), 849/542 (blk)
	Chunk 5 / 10 (11:59:35) ... Done!
	Adinetar-Brachion: 152947 (tot), 5949/60 (reg), 955/630 (blk)
	Chunk 6 / 10 (11:59:53) ... Done!
	Adinetav-Brachion: 149259 (tot), 5118/55 (reg), 828/532 (blk)
	Chunk 7 / 10 (12:00:07) ... Done!
	Adinetas-Adinetas: 608255 (tot), 53925/9 (reg), 39055/9 (blk)
	Chunk 8 / 10 (12:00:28) ... Done!
	Adinetar-Adinetar: 453528 (tot), 46260/11 (reg), 33194/11 (blk)
	Chunk 9 / 10 (12:00:42) ... Done!
	Adinetav-Adinetav: 403019 (tot), 40889/6 (reg), 31327/6 (blk)
	Chunk 10 / 10 (12:00:54) ... Done!
	Brachion-Brachion: 244440 (tot), 47038/12 (reg), 20916/12 (blk)
Defining synteny-constrained orthogroups ... 
	Found 63712 synteny-split OGs for 124547 genes
Found 63712 OGs across 124547 genes. gff3-like text file written to:
	~/Documents/genespace//results/gffWithOgs.txt.gz
Calculating syntenic block breakpoints ... 
	Found 17148 blocks. Text file written to:
	~/Documents/genespace//results/syntenicBlocks.txt.gz:
###############################################################

However there seems to be an issue with rendering the plot:
>plot_riparianHits(gsParam = gpar)
#########################
Reading hits ... Done!
Generating plot coordinates ... Done!
Rendering plot ... Done!
##################################

but no plot is rendered (I am running this directly on the command line and not Rstudio)

**Comment by jtlovell** [comment]
OK - the first error is likely an issue with running `synteny()` without overwrite = T following a failed run. I will need to revisit this error catch. 

The outgroup is a genome that is used in orthofinder, but not in `synteny()`. This lets you correctly specify the evolutionary scale of your orthofinder run without having to include species that are not syntenic in GENESPACE itself. 

In terms of checking which comparisons are not syntenic, `synteny()` outputs the number of hits in blocks etc. It looks like any comparison with "Brachion" is not syntenic. You can see there are only 849 hits in 542 blocks. This isn't much synteny. Have a look at the dotplots in /results and you'll learn more. 

I'm not sure about the plot rendering. I bet it is a problem with your graphics device. Just reset it (run `dev.off()` a couple times until it returns an error).

**Comment by andeast** [comment]
I am having very similar errors to alexvasilikop, so I followed your directions:

> If the error persists, rerun with the following and post the error here.
> 
> ```
> gpar$params$nCores <- 1
> gpar <- synteny(gpar)
> ```
> 
> Setting to a single core will give more informative errors, since the code isn't buried in parallel.

I get the following error:
```
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
Pulling synteny for 6 unique pairwise combinations of genomes
	Running 6 chunks of up to 1 combinations each:
	Chunk 1 / 6 (01:04:42 PM) ... Error in read_blast(path = gsParam$paths$blastDir, ofID1 = ofsp[genome1],  : 
  cannot find /home/andrew/genespace/orthofinder/BlastNA_NA.txt.gz
Calls: synteny ... mclapply -> lapply -> FUN -> parse_blast4synteny -> read_blast
```

I looked at the other Blast files, and they're titled from 0_0 to 2_2. It seems that at least one of my combinations leads synteny to search for an N/A, then fails to find a file titled BlastNA_NA..txt.gz I hope this information proves helpful to you! I'll tell you what I find from here.

**Comment by jtlovell** [comment]
yes. this is a known error that I am working on. set `synteny(gpar, overWrite = TRUE)`. I think that should do it. If not, clear out the /results directory and try synteny again.

**Comment by Kollarlm** [comment]
Hi Jon, I am also having the same issues as above. I went through "Issue #23" as well to see if any of those suggestions were related to this issue. I have tried using the suggested code ...

gpar$params$nCores <- 1
gpar <- set_syntenyParams(gpar, onlyOgAnchors = FALSE, blkSize = 2, nGaps = 20)
gpar <- synteny(gpar, overWrite = TRUE) 

But continue to get the same error as othres in this thread. I have also cleared out the /results directory although nothing was ever in it. This may be something you are still working on but here is my error message. Its mostly identical to the previous error messages in this thread although I did notice after "Found the following counts of arrays / genome:" It never lists the "# genes in # colinear arrays" which I think was similar to issue 23. This may not be helpful. I am using two Mimulus guttatus genomes (different ecotypes) which I have run dot plots for and see that they are syntenic. 

Indexing location of orthofinder results ... Done!
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 50123 global OGs for 50123 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		L1: 32/120, 25284/190, 25284/190
		S1: 35/79, 24514/135, 24514/135
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
Pulling synteny for 3 unique pairwise combinations of genomes
	Running 3 chunks of up to 1 combinations each:
	Chunk 1 / 3 (11:40:54) ... Error in read_blast(path = gsParam$paths$blastDir, ofID1 = ofsp[genome1],  : 
  cannot find /Users/lesliekollar/Desktop/Mimulus_guttatus_nanopore_genome/orthofinder/Results_Aug09/WorkingDirectory/BlastNA_NA.txt.gz

**Comment by jtlovell** [comment]
Hi there, 
This is one of the error catches I need to re-write - its a mismatch between your genome IDs and the orthofinder run (hence `./Results_Aug09/WorkingDirectory/BlastNA_NA.txt.gz`. I'll do it now and push an update today or tomorrow. 
Can you email me (jlovell@hudsonalpha.org) and we can coordinate? I'd like to ensure the catch is working properly with your run. 
Thanks!
John

**Comment by jtlovell** [comment]
The issue here was an old diamond version. The next GENESPACE release will have an error check built in.
