### ISSUE TITLE
The error for "pangenome" step

### ISSUE THREAD

**Issue by zhangzhiyangcs** [jtlovell/GENESPACE#22]
Hi, John
When I used command "pg<-pangenome(gpar)", the error meet me. 

######error log
> pg <- pangenome(gpar)
Building reference-anchored scaffold against A157
        n. ref positions = 29355
        Reading in hits against A157 ... found 1958907
        Interpolating positions ... n. genes mapped: 1x = 2555918, 2+x = 4240, 0x = 303402
        Forming ref.-anchored db ... found 1781745 genes for 29313 placements
Completing the pan-genome annotation ...
        Adding non-anchor entries ... found 163915 genes and 17704 placements
        Checking missing direct ref. syn. OGs ... found 129338 genes and 24344 placements
        Adding indirect syn. OGs ... found 16851 genes and 3132 placements
        Adding syn. OGs without ref. anchor ... found 644795 genes and 160682 placements
        Adding missing genes by synOG identity ... found 126916 genes and 22094 placements
Annotating and formatting pan-genome
        Adding non-anchor entries ... found 600087 genes and 51052 placements
        Adding non-syn. orthologs ... Error in `[.data.table`(x, , c("ofID1", "ofID2", "genome")) :
  column(s) not found: genome
Warning message:
In `[.data.table`(x, , `:=`(ofID1 = idv[paste(gen1, id1)], ofID2 = idv[paste(gen2,  :

**Comment by zhangzhiyangcs** [comment]
I used the beta v0.9.4.

And I  run orthofinder by myself  like this "orthofinder -f 03_pep -op | grep 'diamond blastp' > diamond.commond" to save time. After that I give the corresponding files for [GENESPACE]. 

I will re-run use v0.9.3. Thanks a lot
Zhiyang

**Comment by jtlovell** [comment]
`orthofinder -f 03_pep -op | grep 'diamond blastp' > diamond.commond`
Wow, I'm amazed this works. If using default parameters without a valid `path2orthofinder`, GENESPACE will give you the correct orthofinder commands to run on your cluster. I'd suggest using that method in the future so that the directory structure conforms with GENESPACE.

**Comment by Chenglin20170390** [comment]
Hi, I have the same error `Error in [.data.table(x, , c("ofID1", "ofID2", "genome")) :
column(s) not found: genome` running the pangenome step.

The error solved after changing the sample name of orthofinder files (Orthologues) according to input of genespace.
