### ISSUE TITLE
issue in synteny()

### ISSUE THREAD

**Issue by DrPintoThe2nd** [jtlovell/GENESPACE#23]
Hi Jon,

I've been running into issues at the synteny step of the pipeline. I'm able to successfully complete the full run-through with the test data, but hit issues with my own data. The synteny function hits an error with multiple cores, so I bypassed this in-line with issue #21 and now hit this error, 
```
$`MC_gpar <- synteny(gsParam = MC_gpar)`
`Indexing location of orthofinder results ... Done!
 Parsing the gff files ...
Reading the gffs and adding orthofinder IDs ... Done!
Found 56655 global OGs for 114981 genes
QC-ing genome to ensure chromosomes/scaffolds are big enough...
Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL 
sp1: 32/0, 67033/0, 24628/0
sp2: 16/0, 18211/0, 14776/0    
sp3: 19/0, 29254/0, 29254/0
All look good!
Defining collinear orthogroup arrays ...
Found the following counts of arrays / genome:
sp1: 52351 genes in 9634 collinear arrays
sp2: 3274 genes in 955 collinear arrays                                                                
Pulling synteny for 6 unique pairwise combinations of genomes                                                                   
Running 6 chunks of up to 1 combinations each:                                                                          
Chunk 1 / 6 (10:32:12) ... Error in `[.data.table`(a, , `:=`(scrRank1, 1:.N), by = "ofID1") :
Supplied 2 items to be assigned to group 1 of size 0 in column 'scrRank1'. The RHS length must either be 1 (single values are ok) or match the LHS length exactly. If you wish to 'recycle' the RHS please use rep() explicitly to make this intent clear to readers of your code.`

```
Does this look at all familiar? I'm having trouble understanding exactly what the error is suggesting that I do..
Thanks!
Best,
bjp

**Comment by jtlovell** [comment]
Hi there ... this type of error typically comes up where there is no synteny. I need to write an error catch for this in the next version. There is something very strange about your genomes ... sp1 has way more genes than sp2, nearly all of which are in collinear arrays. I wonder if you parsed your gffs correctly? `52351 genes in 9634 collinear arrays` means that 52k of your genes in sp1 can be condensed into 9.6k representative loci.

**Comment by jtlovell** [comment]
not sure ... are you using the ...translated_cds data from NCBI (see section 4 here: https://htmlpreview.github.io/?https://github.com/jtlovell/GENESPACE/blob/master/doc/genespaceOverview.html)? 

There should not be anywhere near that many genes - check your parsing of the input data. There definitely are different numbers of genes between genomes for a variety of reasons, but two related haploid assemblies should be in the same ballpark. 

If you look at the data from the manuscript here: https://github.com/jtlovell/GENESPACE_data/blob/master/scripts/run_vertebrates.pdf
there should only be 2,727 genes in collinear arrays in chicken ... that was run on an older version of GENESPACE, so the numbers might be a little different.

**Comment by DrPintoThe2nd** [comment]
No, I can't use NCBI files (because they inevitably run into issues as they converge downstream with non-NCBI files, which is most files I work with.. ugh!!). I'm generating my own peptide files using gffread, e.g.

`gffread GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff -g GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna -y GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_peptides.fa`

which generates a nearly identical file to the translated_cds.faa file from NCBI apparently a 5 residue difference somewhere.. lol

```
stats for GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_peptides.fa
sum = 50354732, n = 68754, ave = 732.39, largest = 35463
N50 = 961, n = 14642
N60 = 790, n = 20422
N70 = 638, n = 27513
N80 = 500, n = 36443
N90 = 364, n = 48131
N100 = 31, n = 68754
N_count = 1966527
Gaps = 1878786
-------------------------------------------------------------------------------
stats for GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_translated_cds.faa
sum = 50354737, n = 68754, ave = 732.39, largest = 35463
N50 = 961, n = 14642
N60 = 790, n = 20422
N70 = 638, n = 27513
N80 = 500, n = 36443
N90 = 364, n = 48131
N100 = 31, n = 68754
N_count = 1966527
Gaps = 1878786
-------------------------------------------------------------------------------
stats for GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_protein.faa
sum = 50355184, n = 68683, ave = 733.15, largest = 35463
N50 = 961, n = 14638
N60 = 791, n = 20416
N70 = 638, n = 27504
N80 = 500, n = 36429
N90 = 365, n = 48110
N100 = 31, n = 68683
N_count = 1966481
Gaps = 1878758

```
keeping in mind that I remove non-chromosomal scaffolds before analysis, but:
```
parse_annotations(
  gsParam = gpar, 
  gffEntryType = "mRNA", 
  gffIdColumn = "ID",
  gffStripText = "ID=", 
  headerEntryIndex = 1,
  headerSep = " ", 
  headerStripText = "ID=")

chicken ...
Importing gff ... found 67033 gff entires, and 67033 gene entries
Importing fasta ... found 67078 fasta entires
67033 gff-peptide matches

```

**Comment by jtlovell** [comment]
I'm not sure what is going on here ... maybe you are using each alternative transcript as its own gene? Regardless of method, chicken should have ~25k genes: https://www.ncbi.nlm.nih.gov/genome/annotation_euk/Gallus_gallus/106/

**Comment by DrPintoThe2nd** [comment]
It appears to know there are ~25k genes, if I'm interpreting this correctly: **24628**
```
Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL 
sp1: 32/0, 67033/0, 24628/0
```

Where a quick gene count says: 24335, via
```
awk '$3 == "gene" ' GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff3 | wc -l                                                                                                          
```

Is there a step the `parse_NCBI()` does that `parse_annotations()` does not?

**Comment by jtlovell** [comment]
there are 67k genes there according to how you parsed the gff. If you want to grep "gene", then don't select mRNA (`gffEntryType = "mRNA"`). You probably want `gffEntryType = "gene" ... although other parameters will chance too. 

Yes, `parse_ncbi` does lots of things that `parse_annotations` doesn't (like re-naming the chromosomes etc.). 

In the next release, the `parse_..` functions will be deprecated and GENESPACE will operate solely on bed files, which will make this process smoother.

**Comment by DrPintoThe2nd** [comment]
Hi Jon,

Thanks for your guidance regarding why synteny was failing. I conducted an N+1 across my samples starting with those that were running perfectly and adding sp1, sp2, and sp3 one-at-a-time to that analysis and found that sp3 had a 'code-breaking' issue when parsing the input files. The peptides and gff files had the same transcript ID, but the annotations were directly, or indirectly, generated by Ensembl and the input GFF looked like this "ID=transcript:<Actual_Transcript_Name>". In any case the colon in "transcript:" broke the pipeline and was causing the issues!!

We're now back running at full capacity!
Best,
bjp
