### ISSUE TITLE
error in Combining synteny-constrained and inblock orthogroups ...

### ISSUE THREAD

**Issue by xiaoyezao** [jtlovell/GENESPACE#29]
Hi John,

I got an error when setting `orthofinderInBlk = TRUE`:
```
Combining synteny-constrained and inblock orthogroups ...
	syn OGs: 449963, inblk OGs: 490279Error in `[.data.table`(gff, , list(ofID1 = ofID[-.N], ofID2 = ofID[-1]),  : 
  negative length vectors are not allowed
Calls: synteny -> combine_inblkSynOG -> [ -> [.data.table
In addition: Warning message:
In any(genomeIDs) : coercing argument of type 'character' to logical
Execution halted
```
What's the problem of this?

Thank you in advance.

Tao

**Comment by jtlovell** [comment]
Hi Tao, 
Thanks for this - we are working on this particular error right now. More soon.
John

**Comment by jtlovell** [comment]
huh - actually, this is a new error... what genespace version are you running? can you try v0.9.4 and see if you get the same issue.

**Comment by xiaoyezao** [comment]
This error is from v0.9.4. But the dependencies were installed by conda: 
```
conda install r-data.table r-dbscan r-R.utils r-devtools
conda install bioconductor-Biostrings bioconductor-rtracklayer
```
Could this be the problem? But it works well without `orthofinderInBlk = TRUE`

**Comment by jtlovell** [comment]
It looks like this is an issue where one genome is not at chromosome scale and has no contigs with > 40 genes, which is the minimum for GENESPACE to run orthofinderInBlk. You should either drop the problematic genome or not run orthofinderInBlk.
