### ISSUE TITLE
errors in parse_annotations and parse_ncbi

### ISSUE THREAD

**Issue by DrPintoThe2nd** [jtlovell/GENESPACE#3]
Hi John,

Giving this one last go!

Recap, here's how I downloaded Genespace on my WSL:
```
mamba create -n genespace orthofinder r libgit2
conda activate genespace
R

if (!requireNamespace("devtools", quietly = TRUE))
	install.packages("xml2", dependencies=TRUE, INSTALL_opts = c('--no-lock'))
    install.packages("devtools")
	
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(c("Biostrings", "rtracklayer"))

devtools::install_github("jtlovell/GENESPACE", upgrade = F)

library(GENESPACE)
```

First, I tried to run the example files specified in the tutorial,
Following exactly, I hit this error that pervaded into the next step and I stopped:
```
parse_annotations(
gsParam = gpar,
gffEntryType = "gene",
gffIdColumn = "locus",
gffStripText = "locus=",
headerEntryIndex = 1,
headerSep = " ",
headerStripText = "locus=")

Parsing annotation files ...                                                                                                             
human ...                                                                                                                                
Importing gff ... found 1787 gff entires, and 1787 gene entries                                                                  
Importing fasta ... found 1787 fasta entires                                                                                     
1786 gff-peptide matches                                                                                         
Error in fwrite(gff, file = gsParam$paths$gff[i], sep = "\t") :                                                                    
Compression in fwrite uses zlib library. Its header files were not found at the time data.table was compiled. To enable fwrite compression, please reinstall data.table and study the output for further guidance. 

```
Originally, I had 3 reptile species I was trying to power through GeneSpace, two from ENSEMBL and one formatted for GenBank/NCBI.
In the tutorial, it says  "See 4.1 (using non-standard annotation files).", but I don't see anything like this located in section 4.1. Could a rundown of what exactly GeneSpace wants in the GFF file be here, if it will only accept this very trimmed format of the example files -- it would be nice to know up-front so I can temper my expectations(! haha).
However, upon further reflection and looking at those example files, this appears to be impossible to accommodate without large-scale editing of the gff files.

So to check if I could get _anything_ to parse, I pulled gffs and peptides for 2 wasps from NCBI (https://www.ncbi.nlm.nih.gov/genome/?term=txid32391[orgn] and https://www.ncbi.nlm.nih.gov/genome/104825), uploaded them and parsed using parse_ncbi:
```
gpar <- init_genespace(
genomeIDs = c("wasp1","wasp2"),
speciesIDs = c("wasp1","wasp2"),
versionIDs = c("wasp1","wasp2"),
ploidy = rep(1,2),
diamondMode = "fast",
orthofinderMethod = "fast",
wd = runwd,
nCores = 4,
minPepLen = 50,
gffString = "gff",
pepString = "fa",
path2orthofinder = "orthofinder",
path2mcscanx = "~/MCScanX",
rawGenomeDir = file.path(runwd, "rawGenomes"))

parse_ncbi(gsParam = gpar)

Parsing annotations: wasp1
Reading gff ... found 14119 protein coding genes
Reading peptide fasta ... found 25331 / 14119 total and unique entries
Merging fa and gffError in ncbi_fun(gffIn = gsParam$paths$rawGff[i], gffOut = gsParam$paths$gff[i],  :
PARSING FAILED - is this a ncbi-formatted annotation?   
```

There appears to be alot going on here, I don't know why I'm running into unique errors using different datasets.. especially concerning is the error on the test dataset.

Best,
bjp

**Comment by jtlovell** [comment]
There's definitely a problem with your R and/or R/data.table install - what do you get when you do the following:
```
install.packages("data.table")
library(data.table)
```

Also, looks like you don't have `orthofinder` installed in your conda env (unless it is in your path, then you prob don't want to use conda in the first place). You can check this from R via: 
```
check_orthofinderInstall("orthofinder")
# or
system("orthofinder -h")
```

**Comment by jtlovell** [comment]
A little more information. We have seen this error before when using R installed into a conda env without zlib or incorrectly installed in some other way. 

This is the error of note (this is an R error, not GENESPACE *per se*): 
```
Error in fwrite(gff, file = gsParam$paths$gff[i], sep = "\t") :                                                                    
Compression in fwrite uses zlib library. Its header files were not found at the time data.table was compiled. To enable fwrite compression, please reinstall data.table and study the output for further guidance. 
```
This means that the `zlib` dependency for R is not available for your particular R installation. 

I know of two potential solutions. First is with conda. Try a fresh conda env:
```
conda deactivate # if you are in an existing env
conda create -n genespace_fresh -m
conda activate genespace_fresh
conda install -c bioconda orthofinder
# then get into R or Rstudio
```

The second could be your system's R installation. The best way to resolve this is to uninstall your current R and re-install from CRAN. 

Hope this helps. 
John

**Comment by DrPintoThe2nd** [comment]
Ahhhh.. interesting. Thanks for this information! This appears to be a bit more involved of a fix than I was anticipating (as it usually is!). I'll close this for now and assume that these fixes will work if I had the time to work through them.

If I end up having some time to do a deep dive soon, I'll update this post with how it went -- if not, I hope it helps someone else navigate these potential errors!

Thanks again!!

**Comment by DrPintoThe2nd** [comment]
Hi John, 

I finally had some time and motivation to return to Genespace for a project I started and I went back to this post to work through my issues, the final fix seemed to be installing R dependencies to the conda environment directly when creating it, so I started here and then worked through your tutorial in the repo README:

`mamba create -n genespace orthofinder r libgit2 r-data.table r-devtools r-biocmanager bioconductor-rtracklayer bioconductor-biostrings --yes
`
I'm still hitting some errors further along in the pipeline, but I'm trying to debug and move forward there, if I can't resolve I'll likely open a new issue.

Thanks again!!
Best,
bjp
