### ISSUE TITLE
Output explanation

### ISSUE THREAD

**Issue by sanyalab** [jtlovell/GENESPACE#31]
Hello,

I was hoping that you can direct me to the document that has the explanation of the results. I am looking to find a file or create one that contains syntenic orthogroups. For example if there is a file that contains each orthogroup per line, then that would be useful. Right now I only see pairwise gene ids.

Thanks
Abhijit

**Comment by jtlovell** [comment]
Is the pangenome not what you are looking for? See figure 1 [here](https://elifesciences.org/articles/78526#content). 
Since you are only interested in syntenic orthogroups, that may be too complex. In that case, you can just read in the results/gffWithOgs.txt.gz file and parse via the `synOG` column. If you want one syntenic orthogroup per line, 
```
library(data.table)
g <- fread("results/gffWithOgs.txt.gz")
synOgs <- dcast(g, synOg ~ genome, value.var = "id", fun.aggregate = list)
```

**Comment by sanyalab** [comment]
Hi 

Thank you for replying. I am getting an error when running dcast

`> g <- fread("results/gffWithOgs.txt")`
`> synOgs <- dcast(g, synOg ~ genome, value.var = "id", fun.aggregate = list)`
`Error in eval(x, data, parent.frame()) : object 'synOg' not found`
`> dcast?`
+
>
>
`> synOgs <- dcast(g, synOg ~ genome, value.var = "id", fun.aggregate = list)`
`Error in eval(x, data, parent.frame()) : object 'synOg' not found`

Please advice.
Thanks
Abhijit

**Comment by jtlovell** [comment]
Try with the updated code above. 'synOg' should have been 'synOG'.

**Comment by sanyalab** [comment]
This worked. Thank you. I'll try the pangenome command as well. Thank you for the link.

-Abhijit

**Comment by sanyalab** [comment]
Hello,

Restarting this thread, as I want to know whether there is any automated method to validate the syntelog groupings. 

Thanks
Abhijit

**Comment by jtlovell** [comment]
I'm not sure I'm following. What exactly are you hoping for re: "any automated method to validate the syntelog groupings"

**Comment by jtlovell** [comment]
I think the info you are looking for is in fig 1 [here](https://elifesciences.org/articles/78526.pdf). Each row of the pangenome output data.table object is a set of syntenic orthogroup members. non-syntenic orthologs are included and flagged.

**Comment by jtlovell** [comment]
V1 has a partially functional method to extract this info with `query_genespace`. Hopefully the documentation therein is enough to get moving.
