### ISSUE TITLE
Does inversion regions are more divengent than synteny region  ?

### ISSUE THREAD

**Issue by Chenglin20170390** [jtlovell/GENESPACE#32]
Hi, I have a question about inversion region. Does the inversion region are more divengent than synteny region?  

Can you explan more about how the genespace find inverted region between two genome ? I have some analysis about inverted region.  So, I want to know more about the definition of inversion in genespcae. Thanks in advance.

For example,
I have some inversions between 3 genomes (S1 S2 and S3 see below), I pick up the inverted region between S2 and S3 and select gene ID from S2. I pick up the orthologus gene (og ID(only choose the gene of first one ))from pan-genome anotation pipline of genespcae and pick up the gene of S1 and S3 base on S2 gene ID .  Then do the local alignment to caculate similarity between inverted region (S2 S3)and synteny regions (S1 S2).  Does this work to caculate the similaryty of  inversion/synteny region like the figure below?

For my results,  I alwasy found S1 is  similay to S2 than S3, even S1 have inverison with S2.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/33062118/189952190-7de28e96-0d5a-458d-92c2-5d5349cdc78e.png">

**Comment by jtlovell** [comment]
I'm not sure I 100% follow - if you are asking: "should inverted sequences be more different than non-inverted sequences". If so, I think it depends fully on your genomes and the population/phylo genetic diversity that you are sampling. There are lots of studies showing that inversions affect diversity in systems that hybridize (or freely mate). I doubt inversions would affect diversity at all between species that do not intercross.
