### ISSUE TITLE
gff error

### ISSUE THREAD

**Issue by madhubioinfo** [jtlovell/GENESPACE#33]
I am running the following line parse_annotations(gsParam = gpar,gffEntryType = "gene",gffIdColumn = "locus",gffStripText = "locus=",headerEntryIndex = 1,headerSep = " ",headerStripText = "locus=", troubleshoot = TRUE)

I am getting the following error and I have checked my gff file, and compared with test data look the same I don't know what's wrong
3       funannotate     gene    11115   12539   +       locus=A5FUN_031153
3       funannotate     gene    16751   19151   +       locus=A5FUN_031154
3       funannotate     gene    21860   24354   +       locus=A5FUN_031155
3       funannotate     gene    41603   42543   -       locus=A5FUN_031156
3       funannotate     gene    43494   45514   -       locus=A5FUN_031157
3       funannotate     gene    47846   49410   +       locus=A5FUN_031158
3       funannotate     gene    53230   54461   -       locus=A5FUN_031159
3       funannotate     gene    71058   71486   -       locus=A5FUN_031160
3       funannotate     gene    75252   76684   +       locus=A5FUN_031161
3       funannotate     gene    80171   80985   -       locus=A5FUN_031162
3       funannotate     gene    81141   82352   +       locus=A5FUN_031163
3       funannotate     gene    82528   82961   +       locus=A5FUN_031164

thiis is how my gff file look like
 can you please let me know whats wrong , thanks in advance

**Comment by jtlovell** [comment]
This doesn't look like a gff. if it is (and its /t separated), then it looks like your parsing is OK. what do your fasta headers look like?

**Comment by madhubioinfo** [comment]
3       funannotate     gene    11115   12539   +       locus=A5FUN_031153
3       funannotate     gene    16751   19151   +       locus=A5FUN_031154
3       funannotate     gene    21860   24354   +       locus=A5FUN_031155
3       funannotate     gene    41603   42543   -       locus=A5FUN_031156
3       funannotate     gene    43494   45514   -       locus=A5FUN_031157
3       funannotate     gene    47846   49410   +       locus=A5FUN_031158
3       funannotate     gene    53230   54461   -       locus=A5FUN_031159
3       funannotate     gene    71058   71486   -       locus=A5FUN_031160

 It's a tab-separated file similar to the example dataset
3       BestRefSeq      gene    46948   82996           -               locus=CBWD3
3       Gnomon  gene    443665  650324          +               locus=CHL1
3       Gnomon  gene    662017  708852          -               locus=LOC749565
3       Gnomon  gene    1314492 1627513         +               locus=CNTN6
3       Gnomon  gene    2326368 3286051         +               locus=CNTN4
3       Gnomon  gene    3290182 3339599         -               locus=IL5RA
3       BestRefSeq%2CGnomon     gene    3355512 3380716         +               locus=TRNT1


the protein ids are A5FUN_031153, A5FUN_031155, A5FUN_031154, A5FUN_031157

**Comment by jtlovell** [comment]
if its not a gff3-formatted annotation, `parse_annotations` cannot handle it. Look at the gff3 specs. My guess is you are missing the 6th and 8th columns, which are empty in the example data:
```
3\tBestRefSeq\tgene\t46948\t82996\t\t-\t\tlocus=CBWD3
```

**Comment by madhubioinfo** [comment]
I have fixed my gff file , i need to produce something like this 
![image](https://user-images.githubusercontent.com/10958956/190011783-66c9a291-70c2-4b01-be94-5d5a0f0bc293.png)
 
Do you have any tutorial on that to produce that image?

**Comment by jtlovell** [comment]
see the GENESPACE readme and detailed vignette therein for how to run genespace in general. 
Then to re-create this figure, see the [main script](https://github.com/jtlovell/GENESPACE_data/blob/master/scripts/run_vertebrates.Rmd) and the [script to do the analyses in the paper](https://github.com/jtlovell/GENESPACE_data/blob/master/scripts/vertebrate_analysisFinal.Rmd). Although you will have to use v.0.9.3 to re-create these exactly. 
This will created a figure very similarly to fig2 in the paper, but not precisely - you would need to edit accordingly in Illustrator (or similar) as we detail in the manuscript.
