### ISSUE TITLE
Error in run_orthofinder

### ISSUE THREAD

**Issue by zmz1988** [jtlovell/GENESPACE#38]
Hi, sorry to bother you again. I had successfully run the test data through all the codes listed in the vignette, but now running on my own data resulted me an error in `run_orthofinder` step. Could you please give me some hints where could be wrong? Thanks a lot in advance!

I had successfully paring the annotation and fasta file, and ran the initiate step. But when it comes to orthofinder step, the error comes:

```
> gpar <- run_orthofinder(gsParam = gpar)
Synteny Parameters have not been set! Setting to defaults
	Running 'draft' a.k.a 'fast' genespace orthofinder method 
	############################################################ 
	***NOTE***
	This method should only be used for: 
		(1) closely related diploid species, 
		(2) visualization/genome QC purposes, or 
		(3) inferring orthogroups WITHIN syntenic regions 
	############################################################
Error in fread(file.path(path, "SpeciesIDs.txt"), sep = ":", header = F,  : 
  File '/Genespace_pan-genome/geneSpace/orthofinder/SpeciesIDs.txt' does not exist or is non-readable. getwd()=='/Genespace_pan-genome/geneSpace'
In addition: Warning message:
In system2(gsParam$paths$orthofinderCall, com, stdout = TRUE, stderr = TRUE) :
  running command ''orthofinder' -f /Genespace_pan-genome/geneSpace/peptide -t 10 -a 1 -op -o /Genespace_pan-genome/geneSpace/orthofinder 1>/dev/null 2>&1 2>&1' had status 1

```
I checked the `/Genespace_pan-genome/geneSpace/orthofinder/` folder, and it is empty. Does it mean that probably the parsing of files got something wrong? But I got the gff and the peptide folder in `/Genespace_pan-genome/geneSpace/`, and the files look fine.

**Comment by jtlovell** [comment]
My guess is you have malformed fasta or a bad orthofinder install. If you are willing to wait, v1, which I will release in beta in a week or two will be able to check these better. Otherwise, make sure your peptide fastas are all good (they are in /Genespace_pan-genome/geneSpace/peptide) and that you can call orthofinder > 2.5 from R (`system("orthofinder -h`).

**Comment by zmz1988** [comment]
Thanks for replying me so fast! I checked the fasta, and it seems fine. I show you two lines below. Also the orthofinder has the version 2.5.4. Yes, I could wait, but also would like to roughly run my own test data to see what the problem is.

```
> parse_annotations(
  gsParam = gpar,
  gffEntryType = "mRNA",
  gffIdColumn = "ID",
  gffStripText = "ID=",
  headerEntryIndex = 1,
  headerSep = " ",
  headerStripText = "")
Parsing annotation files ...
	Tair10 ... 
		Importing gff ... found 35386 gff entires, and 35386 mRNA entries
		Importing fasta ... found 76131 fasta entires
		35386 gff-peptide matches
	Done!
	Co ... 
		Importing gff ... found 47876 gff entires, and 47876 mRNA entries
		Importing fasta ... found 47876 fasta entires
		47870 gff-peptide matches
	Done!
	Ca ... 
		Importing gff ... found 46033 gff entires, and 46033 mRNA entries
		Importing fasta ... found 46012 fasta entires
		45999 gff-peptide matches
	Done!
```
`$ ls /Genespace_pan-genome/geneSpace/peptide`
```Ca.fa  Co.fa  Tair10.fa```
`$ less Co.fa`
```
>Cang18989.1
MDINEPSLMDVAHDTINSTQGPALIEVAYFPSSEGKGQGFFRGNSGRVSFRSKGLRIPNPPHQPRTAYVCNGWGGSRRSE
VYRHANHQIRDWAPSQRFDGMAHPIALMSYGNSWLETILMVLISGRNNKNQSPGSLNAELLTLLVRMGVHPKVFPDCMHT
SVSNLVQHGKFH
>Cang18989.2
MTIRNQRFSLLKQPISSTLNQHLVDYPTPSNLSYWWGFGPLAGTMILSVLSSPALVSGLMVARAKNLVHSVLFPIPIFFS
INQLFHYFCRLPIIKHLATKCQLLLFLISHFLLLLVLTKLVLDLGGYLFMDDLSRALSQFVPGFSGGLGGGSNTPPNPSG
DFFLSSYQTSDPDYHDQRRGDSYFSSAPGVQETHRHASGSSTNLHLNLNDQSQDPIFLEVERLSLKCDKVKEKTILKTQS
LLLERGYHIPDERDIERAINVVMTEHETIDIDRRRKRFYYLYSCLGKTGNKFWMELLETLADYNINIKSDSDN



```

**Comment by zmz1988** [comment]
Hi sorry, my bad! I didn't notice that actually one of my .fasta file contains DNA sequence. I didn't get the error message until I run orthofinder separately. Thanks for your fast reply!
