### ISSUE TITLE
errors when parsing ncbi files with parse_annotations() & parse_ncbi()

### ISSUE THREAD

**Issue by laramiemckenna** [jtlovell/GENESPACE#4]
Hi! 

I’ve had great success using GENESPACE to make beautiful multi-species synteny plots with peptide and gff files downloaded from Phytozome but am getting some errors when trying to parse files downloaded from NCBI. 

Right now, I am just trying to run this on some members of Fagales (and got C. illinoinensis and Q. rubra from Phytozome) and I’ve downloaded the GenBank Morella rubra .gff and protein fasta files from this link: [https://www.ncbi.nlm.nih.gov/assembly/GCA_003952965.2/], then renamed them to mrubra_MruZJU_pep.fa and mrubra_MruZJU_gene.gff.

Initially, I tried using the parse_ncbi() function:
```
gpar <- init_genespace(
  genomeIDs = c("qrubra","cillinoinensis","mrubra"),
  speciesIDs = c("qrubra","cillinoinensis","mrubra"),
  versionIDs = c("qrubra","cillinoinensis","mrubra"),
  ploidy = rep(1,3),
  diamondMode = "fast",
  orthofinderMethod = "fast",
wd = runwd,
nCores = 4,
minPepLen = 50,
gffString = "gff",
pepString = "pep",
path2mcscanx = "/Users/laramiesmith/Desktop/MCScanX",
rawGenomeDir = file.path(runwd, "rawGenomes"))

parse_phytozome(gsParam = gpar, overwrite = F, genomeIDs = c("qrubra", "cillinoinensis"))

parse_ncbi(gsParam = gpar, overwrite = F, genomeIDs = c("mrubra"))
```

But, was met with this error: 

```
Parsing annotations: mrubra
	Reading gff ... found 1 protein coding genes
	Reading peptide fasta ... found 29351 / 1 total and unique entries
	Merging fa and gff Error in ncbi_fun(gffIn = gsParam$paths$rawGff[i], gffOut = gsParam$paths$gff[i],  : 
  PARSING FAILED - is this a ncbi-formatted annotation?
```

I suspected that maybe this was related to the fact that in the NCBI files for M. rubra the column ID in the gene files did not exactly match the peptide fasta header. So, I used AGAT and made my own .pep file with matching headers/column IDs using the following command: 

`agat_sp_extract_sequences.pl -g ~/Desktop/mrubra_Mru_ZJU_gene.gff -f ~/Desktop/GCA_003952965.2_Mru_ZJU_2_genomic.fna  -t gene -o ~/Desktop/mrubra_Mru_ZJU_pep.fa
`

After doing this, I was able to use the parse_annotations() command on the M. rubra data without an error, using this: 

```
parse_annotations(
    genomeIDs = c("mrubra"),
    gsParam = gpar,
    gffEntryType = "gene",
    gffIdColumn = "Name",
    gffStripText = " ",
    headerEntryIndex = 2,
    headerSep = " ",
    headerStripText = "name=",
    overwrite = FALSE,
    troubleshoot = TRUE
 )
```

It told me that it found 29351 gff-peptide matches and that the parsing was complete. Then, when I ran this command: 

```
gpar <- run_orthofinder(
    gsParam = gpar)
```

I got the error: 
```

Error in fread(file.path(path, "SpeciesIDs.txt"), sep = ":", header = F,  : 
  File '~/Desktop/GENESPACE_TRIALS/orthofinder/SpeciesIDs.txt' does not exist or is non-readable. getwd()=='/Users/laramiesmith/Desktop/GENESPACE_TRIALS'
```

If I’m only using data from Phytozome, I am able to successfully run orthofinder and the SpeciesID.txt file is made upon giving the command above. However, I cannot get beyond this step when using the NCBI gff file and the .pep file I made from it. 

Any thoughts on how to troubleshoot this? 

Many thanks! 

Cheers,
Laramie

**Comment by jtlovell** [comment]
Thank you Laramie, 
Getting non-standard annotations in order is one of the biggest hangups with genespace. 
I had thought that all NCBI-hosted annotations would have the same format. This is not the case, and that rubra annotation has some complex fasta header structures. 

You were on the right track switching from `parse_ncbi` to `parse_annotations`. I think all you need is to specify the parameters to do the matching. This is a bit of a hack (since we are using each CDS entry), so start and end coordinates won't be right for the whole gene. That said, genespace itself doesn't use these information. Below, I am posting what I think should be the parameters to get a functional match between the gff and fasta headers:

```
parse_annotations(
  gsParam = gpar,
  genomeIDs = "mrubra", # just do the mrubra genome
  gffEntryType = "CDS", # just use column 3 == "CDS" in the gff
  gffIdColumn = "Name", # just use the ";" separated field called "Name"
  headerSep = "\\[", # escape the regular expression and parse fasta header by "["
  overwrite = T, # overwrite the previously parsed annotation files
  gffStripText = " ", # strip off whitespace from the gff CDS names
  headerEntryIndex = 3, # use the 3rd field in the fasta header "[" separated
  headerStripText = ".*=|]| ") # drop any text before and including "=", and exact matches to "]" and whitespace
```

With the properly formatted annotation, you should be able run `run_orthofinder` without any problems.

**Comment by jtlovell** [comment]
Hope this solved the problem. Closing now, but open again if the issue persists.
