### ISSUE TITLE
Different colors for chromosomes in plot_riparianHits()

### ISSUE THREAD

**Issue by aamirwkhan06** [jtlovell/GENESPACE#40]
Hi John,

I have been generating the riparian plot for visualizing the synteny for all the genomes, but I am unable to change colors for the chromosomes. It just gives a single color to all the chromosomes. I tried with different hex codes and later I tried with color codes on the vignettes page. It does not change anything but gives the same color to all chromosomes. Kindly suggest:

ripSouceDat <- plot_riparianHits(
  gpar, refGenome = "genome1",
  genomeIDs = c("genome1", "genome2", "genome3"),
  labelTheseGenomes = c("genome1", "genome2", "genome3"),
  gapProp = .01,
  refChrCols = c("#BC4F43","#F67243","#16645F","#FBBAF7","#F4975F","#CC3333","#1F4A1B"),
  blackBg = FALSE, 
  returnSourceData = T, 
  verbose = F)
        Reading hits ... Done!
        Generating plot coordinates ... Done!
        Rendering plot ... Done!

dev.off()

Thanks for the help!

Kind regards,
Aamir

**Comment by jtlovell** [comment]
Hi Aamir, I have come across this issue and cannot figure it out (it has something to do with the graphics device, you'll see the plot source data has the right colors, I assume) ... genespace v1 is coming shortly and will have a new ggplot2 implemented riparian diagram that for sure will not have this issue. 
In the meantime, if your synteny graph isn't too complicated (and the genomes are all haploid), you can use `plot_riparian` instead, this should make the plot colored as you desire.

**Comment by aamirwkhan06** [comment]
Thanks a lot, John, for your response. "plot_riparian" does the trick for changing the colors of different chromosomes. However, there is another issue. While plotting the synteny the order of chromosomes in the reference genome and all other genomes remain the same, apart from one genome. In this genome it automatically changes the order of chromosomes and they do not match with order as in other genomes. I tried using "reorderChrs = FALSE" but that doesn't seem to work for me.

What might be the issue? Can you please suggest. Other than this the plot looks good and many thanks for a very useful tool.

Thanks and your help is appreciated!

Kind regards,
Aamir

**Comment by jtlovell** [comment]
OK - V1.0.0 is up at the dev branch. There is a simple conversion of your existing data, then a single command to run the entire genespace pipeline (including riparian plot). You can then customize your plots (hopefully). Let me know how that goes.
