### ISSUE TITLE
zlib data.table issue in parse_annotations

### ISSUE THREAD

**Issue by fayweili** [jtlovell/GENESPACE#41]
I encountered an issue when doing the `parse_annotations` step. The message: 

`Error in fwrite(gff, file = gsParam$paths$gff[i], sep = "\t") :  Compression in fwrite uses zlib library. Its header files were not found at the time data.table was compiled. To enable fwrite compression, please reinstall data.table and study the output for further guidance.
`

I tried troubleshooting following https://github.com/jtlovell/GENESPACE/issues/3 but going nowhere. The data.table package seemed to install just fine. Is it possible to have the option of not compressing .gff to get away with this problem? 

Thank you!!

**Comment by jtlovell** [comment]
Hi Fay Wei, any update here? If so, feel free to re-open.
