### ISSUE TITLE
Forcing chromosome order

### ISSUE THREAD

**Issue by aberaslop** [jtlovell/GENESPACE#44]
Dear John, 
I was wondering if there is any way of forcing the order of chromosomes for a particular genome in a plot. For example, in the plot attached: is it possible to move chr 5 ahead of chr9 for Genome1, or chr 6 ahed of chr 3 in Genome2? 
[github_genespace.pdf](https://github.com/jtlovell/GENESPACE/files/9943666/github_genespace.pdf)
As always, thank you so much for your help!!
L.

**Comment by jtlovell** [comment]
Short answer, no in <= v0.9.4, possibly in >=v1.0.0 (beta, see /dev branch). 
In v1 genespace, you have two options for ordering your chromosomes. 
    - `reorderChrsBySynteny = TRUE` (default): orders by synteny with a reference genome (like other versions)
    - `reorderChrsBySynteny = FALSE` use the function specified in the argument `refChrOrdFun` to order all chromosomes. You should be able to write a function that orders your chromosomes the way you want.

**Comment by aberaslop** [comment]
Got it! Will give it a try. Thanks again for this great resource!
