### ISSUE TITLE
Orthofinder error in v1.0.0 dev version

### ISSUE THREAD

**Issue by aamirwkhan06** [jtlovell/GENESPACE#45]
Hi John,

I tried running version 1.0.0 but ended up with orthofinder error:
> gpar <- init_genespace(
  wd = wd, 
  path2mcscanx = "~/pkgs/MCScanX-master/")
Checking Working Directory ... PASS:
        `~/GeneSpace/v1_test/verts`
Checking user-defined parameters ...
        Genome IDs & ploidy ... 
                chicken: 1
                human  : 1
        Outgroup ... NONE
        n. parallel processes ... 10
        collinear block size ... 5
        n gaps in collinear block ... 5
        synteny buffer size... 100
        only orthogroups hits as anchors ... TRUE
        n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
        chicken: 18093 / 18093 geneIDs exactly match (PASS)
        human  : 20627 / 20627 geneIDs exactly match (PASS)
Checking dependencies ...
        Found valid path to OrthoFinder v2.54: `orthofinder`
        Found valid path to DIAMOND2 v2.015: `diamond`
        Found valid MCScanX_h executable: `~/pkgs/MCScanX-master//MCScanX_h`
> gpar <- run_genespace(gsParam = gpar)

############################
1. Running orthofinder (or parsing existing results)
Error in find_ofFiles(orthofinderDir = gsParam$paths$rawOrthofinder) : 
  could not find a valid orthofinder run in orthofinder

Also tried running orthofinder individually
> gpar <- run_orthofinder(gsParam = gpar)
Error in find_ofFiles(orthofinderDir = gsParam$paths$rawOrthofinder) : 
  could not find a valid orthofinder run in orthofinder

When trying to run v1.0.0 with older genespace versions ended up with orthofinder error though a valid orthofinder folder with complete run exists in the working directory.

Kindly suggest.

Thanks!

Kind regards,
Aamir

**Comment by jtlovell** [comment]
Thanks Aamir! I am looking into this right now.

**Comment by jtlovell** [comment]
Hi Aamir, 
I appreciate you giving beta v1 a try; however, I am unable to re-create this particular error. 

I just pushed an update to /dev which strips out dotplotting and simplifies some internal steps. It should make it easier to troubleshoot. Lets figure this out!

Can you make a new working directory and try the code below. Either way, let me know if it errors out.  
John

```
genomeRepo <- "~/path/to/rawGenomeRepo/"
dir.create(file.path(genomeRepo, "chicken1"))
dir.create(file.path(genomeRepo, "human1"))
wd <- "~/path/to/genespaceWD"

detach("package:GENESPACE", unload = TRUE)
devtools::install_github("jtlovell/GENESPACE@dev", upgrade = F)
library(GENESPACE)

download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_translated_cds.faa.gz",
  destfile = file.path(genomeRepo, "human1", "GCF_000001405.40_GRCh38.p14_translated_cds.faa.gz"))
download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_genomic.gff.gz",
  destfile = file.path(genomeRepo, "human1", "GCF_000001405.40_GRCh38.p14_genomic.gff.gz"))

download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/699/485/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_translated_cds.faa.gz",
  destfile = file.path(genomeRepo, "chicken1", "GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_translated_cds.faa.gz"))
download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/699/485/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff.gz",
  destfile = file.path(genomeRepo, "chicken1", "GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff.gz"))


parsedPaths <- parse_annotations(
  rawGenomeRepo = genomeRepo, 
  genomeDirs = c("human1", "chicken1"),
  genomeIDs = c("human", "chicken"),
  presets = "ncbi", 
  genespaceWd = wd)

gpar <- init_genespace(
  wd = wd, nCores = 4,
  path2mcscanx = "~/path/to/MCScanX/")
out <- run_genespace(gpar)
```

**Comment by aamirwkhan06** [comment]
Hi John,

Unfortunately, I end up with the same error with the steps suggested. I am not sure what's happening here. Here's the log of all the steps for running the beta v1:

> library(GENESPACE)
GENESPACE v1.0.0 (pre-release): synteny and orthology constrained
        comparative genomics
> genomeRepo <- "~/GeneSpace/test_v1"
> dir.create(file.path(genomeRepo, "chicken1"))
dir.create(file.path(genomeRepo, "human1"))
> wd<-"~/GeneSpace/test_v1/GeneSpace"
> detach("package:GENESPACE", unload = TRUE)
devtools::install_github("jtlovell/GENESPACE@dev", upgrade = F)
Skipping install of 'GENESPACE' from a github remote, the SHA1 (6bf2000b) has not changed since last install.
  Use `force = TRUE` to force installation
> library(GENESPACE)
GENESPACE v1.0.0 (pre-release): synteny and orthology constrained
        comparative genomics
> download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_translated_cds.faa.gz",
  destfile = file.path(genomeRepo, "human1", "GCF_000001405.40_GRCh38.p14_translated_cds.faa.gz"))
trying URL 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_translated_cds.faa.gz'
Content type 'application/x-gzip' length 17631666 bytes (16.8 MB)
==================================================
downloaded 16.8 MB

> download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_genomic.gff.gz",
  destfile = file.path(genomeRepo, "human1", "GCF_000001405.40_GRCh38.p14_genomic.gff.gz"))
trying URL 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_genomic.gff.gz'
Content type 'application/x-gzip' length 56923273 bytes (54.3 MB)
==================================================
downloaded 54.3 MB

> download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/699/485/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_translated_cds.faa.gz",
  destfile = file.path(genomeRepo, "chicken1", "GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_translated_cds.faa.gz"))
trying URL 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/699/485/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_translated_cds.faa.gz'
Content type 'application/x-gzip' length 11573762 bytes (11.0 MB)
==================================================
downloaded 11.0 MB

> download.file(
  url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/699/485/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff.gz",
  destfile = file.path(genomeRepo, "chicken1", "GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff.gz"))
trying URL 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/699/485/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff.gz'
Content type 'application/x-gzip' length 25161571 bytes (24.0 MB)
==================================================
downloaded 24.0 MB

> parsedPaths <- parse_annotations(
  rawGenomeRepo = genomeRepo, 
  genomeDirs = c("human1", "chicken1"),
  genomeIDs = c("human", "chicken"),
  presets = "ncbi", 
  genespaceWd = wd)
human: n unique sequences = 20627, n matched to gff = 20627
chicken: n unique sequences = 18093, n matched to gff = 18093
> gpar <- init_genespace(
  wd = wd, nCores = 4,
  path2mcscanx = "~/pkgs/MCScanX-master")
Checking Working Directory ... PASS:
        `~/GeneSpace/test_v1/GeneSpace`
Checking user-defined parameters ...
        Genome IDs & ploidy ... 
                chicken: 1
                human  : 1
        Outgroup ... NONE
        n. parallel processes ... 4
        collinear block size ... 5
        n gaps in collinear block ... 5
        synteny buffer size... 100
        only orthogroups hits as anchors ... TRUE
        n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
        chicken: 18093 / 18093 geneIDs exactly match (PASS)
        human  : 20627 / 20627 geneIDs exactly match (PASS)
Checking dependencies ...
        Found valid path to OrthoFinder v2.54: `orthofinder`
        Found valid path to DIAMOND2 v2.015: `diamond`
        Found valid MCScanX_h executable: `~/pkgs/MCScanX-master/MCScanX_h`
> out <- run_genespace(gpar)

############################
1. Running orthofinder (or parsing existing results)
Error in find_ofFiles(orthofinderDir = gsParam$paths$rawOrthofinder) : 
  could not find a valid orthofinder run in orthofinder

These are the subfolders in the 'GeneSpace' folder:
bed dotplots pangenome peptide results riparian syntenicHits tmp

I can see "orthofinder" subfolder does not exist here. Is it that I am not running some steps correctly or some directory structure is incorrect?

Please help.

Thanks!

Kind regards,
Aamir

**Comment by aamirwkhan06** [comment]
Hi John,

Yes, this works. Runs the complete pipeline as well as the orthofinder step.

Thanks!

**Comment by jtlovell** [comment]
Thanks for your patience. I think I'll have to re-structure how genespace finds and vets existing orthofinder runs. Seems like this fix is at least a day or two out. I'll close this issue once I push an update.

**Comment by aamirwkhan06** [comment]
Thanks, John. A couple of things I would like to ask here:

1. I can see in the plot_riparian how can I disable the black background. 'blackBG = FALSE' is not a valid parameter in the updated plot_riparian function.
2. Also, when running plot_riparian function individually to customize the riparian plot it generates *_geneOrder.riparian.pdf. How can I customize and make the corresponding *_bp.riparian.pdf plot?

Thanks!

Best,
Aamir

**Comment by jtlovell** [comment]
Hi Aamir, 
1. Short answer, there is still some functionality that is lacking. Background color will be added at some point. In the meantime, you can load the ggplot2 object and adjust the themes like you would normally. In this case `p + theme(panel.background = element_blank())`. 
2. You can get bp the same way as before, setting `useOrder = FALSE`
