### ISSUE TITLE
Parse_annotations() error subscript out of bounds

### ISSUE THREAD

**Issue by trm76056** [jtlovell/GENESPACE#49]
Hello, 

I am attempting to use this program and had no issues running the test data. Now that i'm running it on my own, I've hit a bit of a wall. I've tried looking through previous issues where I've found a few that provide some insight into what I should do, but alas, I'm still running into problems. I've also tried to format my data so that it mirrors the test data, but am getting an error as follows:

```
Error in tstrsplit(names(fa), headerSep)[[headerEntryIndex]] : 
  subscript out of bounds
```
The program begins to import the gff entries but it seems that once it gets to the fasta it hits a problem. I've also tried playing around with different parameters in the parse_annotation() function, similar to what is described here: https://github.com/jtlovell/GENESPACE/issues/6. I'm happy to share files if that will make it easier, unless you happen to know of what could be causing this error so that I can fix it on my own!

Thanks in advance for the help.

Best,
Theresa

**Comment by jtlovell** [comment]
try running `parse_annotations(..., troubleshoot = TRUE)`. This will print the headers and let you know what is going wrong with the parsing. Alternatively, feel free to print the head of the fasta and gff here and we can help you figure out what parameters you need. Also, are you using v1 (beta release at /dev) or v0.9 (main release)?

**Comment by trm76056** [comment]
Hello,

I am using the main release (0.9) of Genespace. 

I've used the troubleshoot = TRUE to see what is going wrong, and it looks like the IDs for the genes are not being recognized. This is what I see with the output printed and you can see that the ID column has NA for all of them.

```
Parsing annotation files ...
	putrida ... 
		Importing gff ... PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	start_codon	32582331	32582333	.	+	0	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	CDS	32582331	32582796	0.83	+	0	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	exon	32582331	32582796	.	+	.	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	intron	32582797	32582863	0.94	+	.	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	CDS	32582864	32583221	0.42	+	2	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	exon	32582864	32583221	.	+	.	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	intron	32583222	32583284	0.43	+	.	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	CDS	32583285	32583831	0.51	+	1	transcript_id=D.putrida_g3537.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	gene	32582331	32583831	0.35	+	.	transcript_id=D.putrida_g3537
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	transcript	32582331	32583831	0.35	+	.	transcript_id=D.putrida_g3537.t1
[1] 0
found 22381 gff entires                         chr start   end   id strand ord
 1:  Scaffold3__unscaffolded     1  3061 <NA>      -   1
 2: Scaffold10__unscaffolded  2215  2553 <NA>      +   2
 3: Scaffold12__unscaffolded     1   751 <NA>      +   3
 4: Scaffold14__unscaffolded  7999 10297 <NA>      -   4
 5: Scaffold14__unscaffolded  7999 10297 <NA>      -   5
 6: Scaffold14__unscaffolded 10624 13468 <NA>      -   6
 7: Scaffold14__unscaffolded 10624 13468 <NA>      -   7
 8: Scaffold14__unscaffolded 13578 19492 <NA>      -   8
 9: Scaffold14__unscaffolded 28994 40483 <NA>      -   9
10: Scaffold20__unscaffolded     1  4476 <NA>      -  10
, and 22381 transcript entries

**FOUND DUPLICATE GFF ENTRIES. THERE COULD BE A PROBLEM*** 
subsetting to longest model for each gene
		Importing fasta ...  [1] "D.putrida_g1.t1" "D.putrida_g2.t1" "D.putrida_g3.t1" "D.putrida_g4.t1"
 [5] "D.putrida_g5.t1" "D.putrida_10776" "D.putrida_g6.t2" "D.putrida_g6.t3"
 [9] "D.putrida_g6.t1" "D.putrida_g7.t1"
found 23727 fasta entires
 [1] "D.putrida_g1.t1" "D.putrida_g2.t1" "D.putrida_g3.t1" "D.putrida_g4.t1"
 [5] "D.putrida_g5.t1" "D.putrida_10776" "D.putrida_g6.t2" "D.putrida_g6.t3"
 [9] "D.putrida_g6.t1" "D.putrida_g7.t1"
		0 gff-peptide matches
Error in parse_annotations(gsParam = gpar, gffEntryType = "transcript",  : 
  PARSING FAILED - try different parameters
Execution halted
```
 I've been playing around with the different parameters to see what would work, which is why there is an additional error that I've been getting depending on what I put in the command. For the parse_annotations function, I most recently called it like this but have been doing variations of it to try and get it to pull the right information: 

```
parse_annotations(
  gsParam = gpar,
  gffEntryType = "transcript",
  gffIdColumn = "locus",
  gffStripText = "transcript_id=",
  headerEntryIndex = 1,
  headerSep = " ",
  headerStripText = "transcript_id=",
  troubleshoot = TRUE)
```
The head of my gff file is as follows if that helps: 

```
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	stop_codon	21592	21594	.	-	0	transcript_id=D.putrida_g7.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	CDS	21592	21631	1	-	1	transcript_id=D.putrida_g7.t1
PGA_scaffold1__24_contigs__length_33282977	AUGUSTUS	exon	21592	21631	.	-	.	transcript_id=D.putrida_g7.t1
```

My fasta files are like the test fasta files, with the headers just consisting of ">D.putrida_g7.t1".

**Comment by jtlovell** [comment]
Maybe you stripped off the 9th column from your gff3-formatted annotation? For GENESPACE to work, you need a gff with rows that contains, for example `D.putrida_g7.t1` in the 9th column

**Comment by trm76056** [comment]
The gff files (as far as I'm aware) have 9 columns (starting from 1). I looked back at the format too, and I believe I have all that information as I didn't remove anything, just tried to format the last column so that it was simpler and had just then name of the gene.

**Comment by jtlovell** [comment]
Ah, I see it now (it was off my screen)
I think the problem is that there is no 'locus' gffIdColumn. I'm pretty sure the parameterization you want is
```
parse_annotations(
  gsParam = gpar,
  gffEntryType = "transcript",
  gffIdColumn = "transcript_id",
  headerEntryIndex = 1,
  headerSep = " ",
  headerStripText = "transcript_id=",
  troubleshoot = TRUE)
```

**Comment by trm76056** [comment]
When I use that command, it gives me the error: `unused argument (gffIDColumn = "transcript_id")`. When I've tried removing that to see if that fixes the problem, I get the error: `PARSING FAILED - try different parameters`. The output before these looks pretty much the exact same as what I have above as well.

**Comment by jtlovell** [comment]
Not sure. You could attach a the files here and I can get you the parameters. Or, you could try v1 at /dev which allows you to do the parsing yourself.

**Comment by trm76056** [comment]
[D.putrida.zip](https://github.com/jtlovell/GENESPACE/files/10077467/D.putrida.zip)
 I have the peptide and gff files attached here for one of the species I'm working with. Working with v1 requires me to request an update through our bioinformatics core and that'll take some time, so if I can get it working with the main release then that'll be easier, but ultimately if I need to update I can!

Thanks for the help so far.

**Comment by jtlovell** [comment]
I'm not sure. The params I shared above worked fine. I downloaded the annotations, then put them in `~/Downloads/D.putrida/vx/annotation`

```
wd <- "~/Downloads/test"
ra <- "~/Downloads"
gpar <- init_genespace(
    genomeIDs = c("tmp1", "tmp2"),
    speciesIDs = c("D.putrida", "D.putrida"),
    versionIDs = c("vx", "vx"),
    ploidy = 1,
    wd = wd,
    nCores = 6,overwrite = T,
    path2orthofinder = "orthofinder",gffString = "gff", pepString = "fa",
    path2mcscanx =  "~/programs/MCScanX/",
    rawGenomeDir = ra)

parse_annotations(
    gsParam = gpar,
    gffEntryType = "transcript",
    gffIdColumn = "transcript_id",
    headerEntryIndex = 1,
    headerSep = " ",
    headerStripText = "transcript_id=")
```

**Comment by trm76056** [comment]
Hello, when I use your code, I am still getting an error that says there is an unused argument: 
```
Error in parse_annotations(gsParam = gpar, gffIDColumn = "transcript_id",  : 
  unused argument (gffIDColumn = "transcript_id")
```

This is the entirety of my code, which I believe is on par with what you have. 

```
runwd <- file.path("~/Genome_Evolution/Synteny_Genespace")

gids <- c("putrida", "neotestacea")
gpar <- init_genespace(
  genomeIDs = gids,
  speciesIDs = gids,
  versionIDs = gids,
  ploidy = 1,
  wd = runwd,
  gffString = "braker.gff",
  pepString = "pep",
  path2orthofinder = "/apps/eb/OrthoFinder/2.5.4-foss-2020b/bin/orthofinder",
  path2mcscanx = "/apps/eb/MCScanX/20220327-GCC-10.2.0-Perl-5.32.0",
  rawGenomeDir = file.path(runwd, "rawGenomes"))

parse_annotations(
  gsParam = gpar,
  gffIDColumn = "transcript_id",
  gffEntryType = "transcript",
  headerEntryIndex = 1,
  headerSep = " ",
  headerStripText = "transcript_id=",
  troubleshoot = TRUE)
```

**Comment by jtlovell** [comment]
try `gffIdColumn` instead of `gffIDColumn`.

**Comment by trm76056** [comment]
Typos are going to be the bane of my research existence. That worked perfectly and finished super fast! Thank you for the help and patience working through this with me. Its a great program!

**Comment by jtlovell** [comment]
ok. glad it worked!
