### ISSUE TITLE
"Can't find gff-like file" when running synteny 

### ISSUE THREAD

**Issue by ariellerjohnson** [jtlovell/GENESPACE#5]
Hi, 

I am a PhD student trying to run the test example.  Everything goes smoothly until the step "gpar <- synteny (gsParam = gpar), at which point I get this error: 

> gpar <- synteny(gsParam = gpar)
Indexing location of orthofinder results ... Done!
Can't find gff-like file, but overwriteGff = TRUE, setting to FALSE
Can't find all synhits files, but overwriteHits = TRUE, setting to FALSE
Can't find blk coords, but overwriteBlks = TRUE, setting to FALSE
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Done!
	Found 1963 global OGs for 5616 genes
	QC-ing genome to ensure chromosomes/scaffolds are big enough...
      		Genome: n. chrs PASS/FAIL, n. genes PASS/FAIL, n. OGs PASS/FAIL
		chimp: 2/0, 1926/0, 1851/0
		human: 2/0, 1786/0, 1719/0
		rhesus: 2/0, 1904/0, 1836/0
	All look good!
	Defining collinear orthogroup arrays ... 
	Found the following counts of arrays / genome:
		chimp: 96 genes in 34 collinear arrays
		human: 94 genes in 30 collinear arrays
		rhesus: 96 genes in 37 collinear arrays
Pulling synteny for 6 unique pairwise combinations of genomes
	Running 1 chunks of 20 combinations each:
	Chunk 1 / 1 (05:08:06 PM) ... Done!
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(1:nrow(splSynp[[i]]), mc.cores = nCores, function(j) { :
  scheduled cores 1, 6, 4, 2, 5 encountered errors in user code, all values of the jobs will be affected

Any idea what could be causing this?  I tried with my own data and got a similar error. 

Thank you!!

Best, 
Arielle

**Comment by jtlovell** [comment]
Thank you Arielle,
You found a bug and I was able to reproduce it. I really appreciate it. 

The issue was with the pairwise dotplot plotting window (you can always see a more informative error by setting the number of cores to 1 in the `init_genespace` step). 

Anyways, it is fixed and an update has been pushed to the 'master' branch. Please try re-installing GENESPACE and giving it and re-running (you might need to set `overwrite = T` in `synteny`). 

If something else isn't working, please follow up here. Thanks for using GENESPACE!
Cheers, 
John

**Comment by ariellerjohnson** [comment]
John, 

Wow, thank you so much for the really quick response!!  I deleted my directories from the previous run, then re-installed GENESPACE and got the following error: 

> remove.packages("GENESPACE")
Removing package from ?/home/FrankLab/arj66/R/x86_64-pc-linux-gnu-library/4.0?
(as ?lib? is unspecified)
> if (!requireNamespace("devtools", quietly = TRUE))
+   install.packages("devtools")
> devtools::install_github("jtlovell/GENESPACE", upgrade = F)
Downloading GitHub repo jtlovell/GENESPACE@HEAD
?  checking for file ?/tmp/Rtmpx4WITU/remotes92c6ba28155/jtlovell-GENESPACE-31af595/DESCRIPTION? (416ms)
?  preparing ?GENESPACE?:
?  checking DESCRIPTION meta-information ...
?  checking for LF line-endings in source and make files and shell scripts
?  checking for empty or unneeded directories
?  building ?GENESPACE_0.9.3.tar.gz?
   
Installing package into ?/home/FrankLab/arj66/R/x86_64-pc-linux-gnu-library/4.0?
(as ?lib? is unspecified)
* installing *source* package ?GENESPACE? ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (GENESPACE)
> library(GENESPACE)
> runwd <- file.path("/local/workdir/arj66/GENESPACE/test")
> make_exampleDataDir(writeDir = runwd)
Error: lazy-load database '/home/FrankLab/arj66/R/x86_64-pc-linux-gnu-library/4.0/GENESPACE/R/GENESPACE.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -3 in R_decompress1 

Let me know if I'm making an error or whether it's another bug!  Thanks!

Best, 
Arielle

**Comment by ariellerjohnson** [comment]
John, 

Yep, you're right, I just had to re-open R before I reinstalled.  It's working now.  Thank you very much!!

Best, 
Arielle
