### ISSUE TITLE
Error with small regions of interest

### ISSUE THREAD

**Issue by epacht** [jtlovell/GENESPACE#50]
I made a comparative map between cattle and sheep and am trying to highlight hyper-hydroxymethylated regions that are only a few hundred to a few thousand base pairs long. I have tried multiple of these and when I try to highlight these I get the following error:
Error in `[.data.table`(gf, , `:=`(ord, 1:.N), by = "genome") : 
  Supplied 2 items to be assigned to group 1 of size 0 in column 'ord'. The RHS length must either be 1 (single values are ok) or match the LHS length exactly. If you wish to 'recycle' the RHS please use rep() explicitly to make this intent clear to readers of your code.
When I try to highlight a random 800,000bp region it highlights fine and I do not get an error. I am wondering if there is a minimum length needed for regions of interest and if there are any ways to get around that?

**Comment by jtlovell** [comment]
hmm. This is v0.9, right? Is it possible that your small region doesn't contain any genes? If not, this sounds like a bug. I'd love to help, but won't be able to until after the USA thanksgiving holiday.

**Comment by epacht** [comment]
Yes, it is version 0.9. I annotated my regions and pulled out only those that had genes and am still getting the same error. Thank you for your help.

**Comment by jtlovell** [comment]
I'm not sure what might be causing this. pls reach out to me via email jlovell[at]hudsonalpha[dot]org and we can figure this out.

**Comment by jtlovell** [comment]
FYI. GENESPACE v1.1.3 is at /dev. Thanks for the help here. Querying utilities and position highlights in riparian plots are now in there.
