### ISSUE TITLE
Cannot find orthofinder

### ISSUE THREAD

**Issue by hellebaa** [jtlovell/GENESPACE#51]
Hi! I am running the example dataset:
```
gids <- c("human","chimp","rhesus")
gpar <- init_genespace(
  genomeIDs = gids, 
  speciesIDs = gids, 
  versionIDs = gids, 
  ploidy = rep(1,3),
  wd = runwd, 
  gffString = "gff", 
  pepString = "pep",
  path2orthofinder = "orthofinder", 
  path2mcscanx = "~/Applications/MCScanX",
  rawGenomeDir = file.path(runwd, "rawGenomes"))

```
**I get output:** 
Initializing GENESPACE run
	checking genomeIDs ... PASS (human, chimp, rhesus)
	checking outgroup ... PASS (no outgroup)
	checking ploidy ... PASS (1, 1, 1)
	checking the number of parallel processes ... PASS (4)
	Verbosity ... PASS (TRUE)
	minPepLen ... PASS (20)
	checking working directory ... PASS (~/Desktop/testGenespace)
	checking parsed gff files ... PASS (/Users/hellebaalsrud/Desktop/testGenespace/gff)
	checking parsed peptide files ... PASS (/Users/hellebaalsrud/Desktop/testGenespace/peptide)
Checking dependencies and 3rd party installations
	MCScanX installation ... Warning: 'length(x) = 14 > 1' in coercion to 'logical(1)'PASS (/Users/hellebaalsrud/Applications/MCScanX/MCScanX_h)
	Orthofinder installation ... no installation found at orthofinder
	OrthoFinder method ... PASS - (default)

	######***NOTE***########
	You will need to conduct an orthofinder run outside of R prior to using GENESPACE
	Follow instructions printed from run_orthofinder

	Orthofinder in block method ... PASS (FALSE)
GENESPACE run successfully initialized
	results will be stored in ~/Desktop/testGenespace/results

**How to solve this? I have checked that orthofinder is installed. I have opened interactive Rstudio. I have tried giving it the full path to where orthofinder is installed. All help is appreciated**

**Comment by jtlovell** [comment]
Did you open Rstudio from the shell env where orthofinder is in the path? If not, then the path `path2orthofinder = "orthofinder"` won't give you a valid install. Your options are to either: 1) run orthofinder separately from the shell (`run_orthofinder` will give you run instructions), 2) open Rstudio from the shell env with `open -na rstudio` or 3) pass `path2orthofinder = "path/to/valid/orthofinderInstall"`

**Comment by jtlovell** [comment]
To use option 1, just call `run_orthofinder()` as you normally would and follow the instructions printed to the console. 
If you have `orthofinder` in the path, and opened your R session from that shell environment, then you should be able to call orthofinder from R. This clearly isn't the case, maybe there is something up with your system? you can check to be sure by running in R `system("orthofinder -h")`. If this doesn't work, then you know you have a problem with your `$PATH`. Then you can try in R `system("/User/opt/anaconda3/envs/orthofinder/bin/orthofinder -h")`. If this doesn't work, then you know you have a problem with your orthofinder install. Hope this helps.

**Comment by hellebaa** [comment]
Thank you, I finally figured it out now! I got a warning: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4. So I installed an older version of numpy in my orthofinder environment and now everything seems to be working.

**Comment by sashulkaSh** [comment]
> To use option 1, just call `run_orthofinder()` as you normally would and follow the instructions printed to the console. If you have `orthofinder` in the path, and opened your R session from that shell environment, then you should be able to call orthofinder from R. This clearly isn't the case, maybe there is something up with your system? you can check to be sure by running in R `system("orthofinder -h")`. If this doesn't work, then you know you have a problem with your `$PATH`. Then you can try in R `system("/User/opt/anaconda3/envs/orthofinder/bin/orthofinder -h")`. If this doesn't work, then you know you have a problem with your orthofinder install. Hope this helps.

Hello! 
command system("/User/opt/anaconda3/envs/orthofinder/bin/orthofinder -h") works, but inside the GENESPACE - provide the full path "~/OrthoFinder_source/orthofinder.py" - doesnt work..
