### ISSUE TITLE
run_orthofinder

### ISSUE THREAD

**Issue by AbirUl12** [jtlovell/GENESPACE#54]

**Comment by AbirUl12** [comment]
Please check this out. Why am I facing this problem? I am running your example data.

> gpar <- run_orthofinder(
+   gsParam = gpar)
Synteny Parameters have not been set! Setting to defaults
	Running 'draft' a.k.a 'fast' genespace orthofinder method 
	############################################################ 
	***NOTE***
	This method should only be used for: 
		(1) closely related diploid species, 
		(2) visualization/genome QC purposes, or 
		(3) inferring orthogroups WITHIN syntenic regions 
	############################################################
		Running 1/6 (chimp vs. chimp)
		Running 2/6 (chimp vs. rhesus)
		Running 3/6 (rhesus vs. rhesus)
		Running 4/6 (chimp vs. human)
		Running 5/6 (rhesus vs. human)
		Running 6/6 (human vs. human)
		Done!
	Inverting intergenomic files ... Error in fwrite(tmp, sep = "\t", quote = FALSE, col.names = FALSE, row.names = FALSE,  : 
  Compression in fwrite uses zlib library. Its header files were not found at the time data.table was compiled. To enable fwrite compression, please reinstall data.table and study the output for further guidance.

**Comment by jtlovell** [comment]
My guess is there is something wrong with your orthofinder install. Are you running diamond2 and orthofinder >= 2.5.4?

**Comment by AbirUl12** [comment]
I download through this comments:
conda create -n orthofinder
conda activate orthofinder
conda install -c bioconda orthofinder

from your github link. https://github.com/jtlovell/GENESPACE

**Comment by jtlovell** [comment]
yup. but depending on your system, you might have old versions. have a look at the installed versions.

**Comment by AbirUl12** [comment]
Thank you very much for your concern. I check the version of ortholog 2.5.4. It is alright. 
i think when I run this
> gpar <- init_genespace(
+   genomeIDs = c("human","chimp","rhesus"),
+   speciesIDs = c("human","chimp","rhesus"),
+   versionIDs = c("human","chimp","rhesus"),
+   outgroup = NULL,
+   ploidy = rep(1,3),
+   diamondMode = "fast",
+   orthofinderMethod = "fast",
+   wd = runwd,
+   orthofinderInBlk = FALSE, 
+   overwrite = F, 
+   verbose = T,
+   nCores = 4,
+   minPepLen = 50,
+   gffString = "gff",
+   pepString = "pep",
+   path2orthofinder = "orthofinder",
+   path2diamond = "diamond",
+   path2mcscanx = "~/MCScanX",
+   rawGenomeDir = file.path(runwd, "rawGenomes"))
Initializing GENESPACE run
	checking genomeIDs ... PASS (human, chimp, rhesus)
	checking outgroup ... PASS (no outgroup)
	checking ploidy ... PASS (1, 1, 1)
	checking the number of parallel processes ... PASS (4)
	Verbosity ... PASS (TRUE)
	minPepLen ... PASS (50)
	checking working directory ... PASS (~/Desktop/testGenespace)
	checking parsed gff files ... PASS (/Users/abirulislam/Desktop/testGenespace/gff)
	checking parsed peptide files ... PASS (/Users/abirulislam/Desktop/testGenespace/peptide)
Checking dependencies and 3rd party installations
	MCScanX installation ... PASS (/Users/abirulislam/MCScanX/MCScanX_h)
	Orthofinder installation ... PASS (orthofinder)
	OrthoFinder method ... PASS - (fast)
	Orthofinder in block method ... PASS (FALSE)
	diamond mode ... PASS (--fast)
GENESPACE run successfully initialized
	results will be stored in ~/Desktop/testGenespace/results
Warning messages:
1: In !grepl("prefix_fn", chk[1]) || is.na(chk) :
  'length(x) = 14 > 1' in coercion to 'logical(1)'
2: In !grepl("OrthoFinder", ver[2]) || is.na(ver) :
  'length(x) = 58 > 1' in coercion to 'logical(1)'
3: In !grepl("OrthoFinder", ver[2]) || is.na(ver) :
  'length(x) = 58 > 1' in coercion to 'logical(1)'
4: In !grepl("OrthoFinder", ver[2]) || is.na(ver) :
  'length(x) = 58 > 1' in coercion to 'logical(1)'


this warning message may be a problem. If not, you know better.
Please have a look.

**Comment by jtlovell** [comment]
that warning message is not a problem - its an issue with v0.9.4 that I am not going to address. 
I have seen the orthofinder issue you have here ... it it always due to an old orthofinder or diamond version. if you are running orthofinder >= 2.5.4 and diamond >= v2.0.14.152, then I am not sure what is going on. I'd say just switch over to v1 at /dev, which should work fine.

**Comment by AbirUl12** [comment]
can you suggest how to switch over to v1 at /dev? I can not find any script or command on your GitHub site.

**Comment by jtlovell** [comment]
you can click on the drop down or just go here: https://github.com/jtlovell/GENESPACE/tree/dev
There is a new readme there. 
To re-install v1 genespace, you need to detach your existing install. 

```
detach("package:GENESPACE", unload = TRUE)
devtools::install_github("jtlovell/GENESPACE@dev", upgrade = F)
library(GENESPACE)
```
