### ISSUE TITLE
MCScanX installation 

### ISSUE THREAD

**Issue by shyunchoi** [jtlovell/GENESPACE#57]
Hello,
I tried running pre-analysis on the test file before turning mine.
An error occurred while running the script through R studio on Windows.

**###
While setting up the MCScanX directory
MCScanX installation ... Error in check_MCScanXhInstall(path2mcscanx) :
   cannot find MCScanX_h executable inNA
###**

The script I am running is this.

**## path
setwd("C:/Users/USER/OneDrive /바탕 화면/Data/comparative/genespace")
getwd()

##genespace_install

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("Biostrings")

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("rtracklayer")

install.packages("remotes")
remotes::install_github("jtlovell/GENESPACE")

library(GENESPACE)
  runwd <- file.path("C:/Users/USER/OneDrive/바탕 화면/Data/comparative/testGenespace")

  if(dir.exists(runwd))
    unlink(runwd, recursive = T)

  make_exampleDataDir(writeDir = runwd)

  list.files(runwd, recursive = T, full.names = F)
  
gids <- c("human","chimp","rhesus")
gpar <- init_genespace(
  genomeIDs = c("human","chimp","rhesus"),
  speciesIDs = c("human","chimp","rhesus"),
  versionIDs = c("human","chimp","rhesus"),
  outgroup = NULL,
  ploidy = rep(1,3),
  diamondMode = "fast",
  orthofinderMethod = "fast",
  wd = runwd,
  orthofinderInBlk = FALSE, 
  overwrite = F, 
  verbose = T,
  nCores = 4,
  minPepLen = 50,
  gffString = "gff",
  pepString = "pep",
  path2orthofinder = "orthofinder",
  path2diamond = "diamond",
  path2mcscanx = "C:/Users/USER/OneDrive //Data/comparative/MCScanX",
  rawGenomeDir = file.path(runwd, "rawGenomes"))**

Everything was fine until I got the error.
I downloaded my Othofinder and MCScanX from github, unzipped them and placed them in the path I want to run.

**Comment by jtlovell** [comment]
Hi there.
This error happens when you do not provide a valid path to your MCScanX install. So, can you confirm that you have a complete MCScanX installation. 
You can do this, where `path2mcscanx` is the path you are providing to `init_genespace(..., path2mcscanx)`. 

```
pth <- file.path(path2mcscanx, "MCScanX_h")
chk <- system2(pth, "-h", stdout = TRUE, stderr = FALSE)
print(chk)
```

If this returns the help file for MCScanX, then you know you have a good install. Otherwise, that is your problem. 

Also, it is worth noting that I have never tried GENESPACE or any of its dependencies on a windows machine and have no idea if things will behave normally.  

Let me know if this helps, 
John

**Comment by shyunchoi** [comment]
I will try to proceed again.
thank you so much.


보낸 사람: John ***@***.***>
보낸 날짜: 2023년 1월 10일 화요일 오전 11:31
받는 사람: ***@***.***>
참조: ***@***.***>; ***@***.***>
제목: Re: [jtlovell/GENESPACE] MCScanX installation (Issue #57)


Hi there.
This error happens when you do not provide a valid path to your MCScanX install. So, can you confirm that you have a complete MCScanX installation.
You can do this, where path2mcscanx is the path you are providing to init_genespace(..., path2mcscanx).

pth <- file.path(path2mcscanx, "MCScanX_h")

chk <- system2(pth, "-h", stdout = TRUE, stderr = FALSE)

print(chk)

If this returns the help file for MCScanX, then you know you have a good install. Otherwise, that is your problem.

Also, it is worth noting that I have never tried GENESPACE or any of its dependencies on a windows machine and have no idea if things will behave normally.

Let me know if this helps,
John
