### ISSUE TITLE
Custom ordering of chromosomes

### ISSUE THREAD

**Issue by Neato-Nick** [jtlovell/GENESPACE#59]
Is it possible to manually change the order chromosomes are plotted?
I'm really quite impressed with the natural sort to show reference chromosomes in ascending numerical order no matter what the prefixes are, but I'd like to override this sometimes.
I have a genome with chr1, chr2, ..., chrN and scaf_1, scaf_2, scaf_3. Right now it's plotting:
chr1 -> scaf_1 -> chr2 -> scaf_2 -> ... -> chrN
I would rather plot :
chr1 -> chr2 -> ... -> chrN -> scaf_1 -> scaf_2 -> scaf_3

I was thinking of using the returnSourceData option and modifying the values in $chrPos$chr but I'm worried that would throw off other values.

I'm sorry this isn't reproducible on your end, but here's the code I'm using and an example plot
```
plot_genomes <- c("na1", "pinf")
plot_riparianHits(gpar_outs_illum,
                  genomeIDs = plot_genomes,
                  refGenome = "na1",
                  chrLabFun = function(x) gsub("^0", "", gsub("^chr|^scaffold|^lg", "", tolower(x))),
                  blackBg = FALSE)
```
![image](https://user-images.githubusercontent.com/5849554/213299654-2ce7dca5-652a-4ad4-a9e4-6b0b15cdea58.png)

**Comment by jtlovell** [comment]
Hi there, 
Short answer, no ... but there will be, probably as an update in mid spring. 
Long answer, yes ... but you really need to trick GENESPACE into doing it. There is an argument: `chrLabFun`. You'd set `reorderChrs = FALSE` (do not re-order by synteny, just use name of chromosomes as the order), then provide `chrLabFun` with a function that will put an ordered character string at the beginning of the the chromosome names in the order you'd like. This is tricky to do, be feasible. 

Look out for the first full v1 release, which should be late this winter. I'll try to add a `chrOrderDict` argument that will take the orders of chromosomes within genomes. 
John

**Comment by jtlovell** [comment]
you would make a dictionary `c("Chr1_genome1:04", "Chr2_genome1:01", "ChrN_genome2:19")` or whatever, then parse and query this dictionary for each chromosome name. If I wasn't working currently on a better way to do it, I'd provide an example ... just don't have the bandwidth currently. More soon.

**Comment by Neato-Nick** [comment]
This was a great idea but it looks like chrLabFun is parsed after the chromosomes are sorted for the visual. I might've implemented your suggestion wrong.
"14" still ended up between "1" and "2", owing to its original value of "scaf_1"
![image](https://user-images.githubusercontent.com/5849554/213828233-9369dbac-4f8d-4cdd-b9b0-b22764903443.png)
```
chr_dict <- c("pchr1" = 1, "pchr2" = 2, "pchr3" = 3, "pchr4" = 4, "pchr5" = 5,
              "pchr6" = 6, "pchr7" = 7, "pchr8" = 8, "pchr9" = 9, "pchr10" = 10,
              "pchr11" = 12, "pchr12" = 12, "pchr13" = 13,
              "scaf_1" = 14, "scaf_2" = 15, "scaf_3" = 16, "uctg_1" = 17)
chr_dict_char <- as.character(chr_dict)
names(chr_dict_char) <- names(chr_dict)
plot_genomes <- c("pr102chr", "eu1chr")
plot_riparianHits(gpar_chr,
                  genomeIDs = plot_genomes,
                  refGenome = "pr102chr",
                  chrLabFun = function(x) str_replace_all(x, chr_dict_char),
                  blackBg = FALSE)
```

**Comment by Neato-Nick** [comment]
I read your code and I see there is no explicit sorting in plot_riparianHits except reorderChrs. It's just plotting by linear position of the gene in the genome. Going back to my GFF I see that's where the issue starts, so a solution would need to override that positional data. I see some really clever use of that gene positioning, I understand now that this issue will not be as simple as I'd hoped. e.g of my gff
```
seq     gene_num
pchr1     1999
pchr1     2000
scaf_1     2001
...
scaf_1     2499
pchr2     2500
pchr2     2001

**Comment by jtlovell** [comment]
Cleverly written function! Nice work. Too bad it didn't work. 

Well, thats embarrassing - looks like you know this code better than I do. It sounds like you are volunteering to write this? jk (sorta). 
I have one other synteny issue/improvement that takes priority. Once thats fixed, I'll get to this in V1 `plot_riparian`, which is a ground-up re-write, should be easy to get this incorporated. 

Appreciate the patience and sorry about leading you down the wrong path.

**Comment by Neato-Nick** [comment]
I wish I had the bandwidth for it, too! Makes sense to focus on implementation in the re-write. To work around this issue, I will just create separate riparian plots for my different chr prefixes using the OnlyTheseRegions arg. Thank you for exchanging info with me!

**Comment by jtlovell** [comment]
FYI. GENESPACE v1.1.3 is at /dev. Thanks for the help here. Querying utilities and position highlights in riparian plots are now in there. You can also now give it a vector of chromosome that force the order of the reference genome. Unfortunately, custom ordering of ALL genomes is too hard to implement ...
