### ISSUE TITLE
GFF parsing issue

### ISSUE THREAD

**Issue by ariellerjohnson** [jtlovell/GENESPACE#6]
Hi again, 

The test dataset works great for me, but when I try to run synteny on my own data I have been getting the error: 
`
gpar <-  synteny(gsParam=gpar, overwrite = T)
Indexing location of orthofinder results ... Done!
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Error in rbindlist(lapply(names(gffFiles), function(i) { : 
  Item 5 has 7 columns, inconsistent with item 1 which has 8 columns. To fill missing columns use fill=TRUE.
`

I think this is what might be going on: I have been feeding several different gff file types into GENESPACE for parsing.  GENESPACE tells me that it has successfully parsed all the files, but it looks like GENESPACE has been including an "nbp" column for the gff's parsed using parse_annotations() but not parse_phytozome() which could explain my error.  It looks like this could have to do with the part of the code where GENESPACE is trying to pick the longest gene model for each gene?  It seems to not be identifying which gff features are CDS entries, if I'm reading the output right.  

Here is part of my output: 

`
> parse_annotations(
+   genomeIDs = c("Hevea brasiliensis", "Jatropha curcas"),
+   gsParam = gpar,
+   gffEntryType = "CDS",
+   headerEntryIndex = 1,
+   overwrite = T,
+   troubleshoot = T,
+   headerSep=" ")
Parsing annotation files ...
	Hevea brasiliensis ... 
		Importing gff ... CM021226.1	Genbank	region	1	74039119	.	+	.	ID=CM021226.1:1..74039119;Dbxref=taxon:3981;Name=1;chromosome=1;country=China: Yunnan;cultivar=GT1;gbkey=Src;genome=chromosome;mol_type=genomic DNA;tissue-type=leaf
CM021226.1	Genbank	gene	3335	5600	.	+	.	ID=gene-GH714_038397;Name=GH714_038397;gbkey=Gene;gene_biotype=protein_coding;locus_tag=GH714_038397
CM021226.1	Genbank	mRNA	3335	5600	.	+	.	ID=rna-gnl|WGS:JAAGAX|GT039715.t1;Parent=gene-GH714_038397;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
CM021226.1	Genbank	exon	3335	3537	.	+	.	ID=exon-gnl|WGS:JAAGAX|GT039715.t1-1;Parent=rna-gnl|WGS:JAAGAX|GT039715.t1;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
CM021226.1	Genbank	exon	3903	3965	.	+	.	ID=exon-gnl|WGS:JAAGAX|GT039715.t1-2;Parent=rna-gnl|WGS:JAAGAX|GT039715.t1;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
CM021226.1	Genbank	exon	4098	4214	.	+	.	ID=exon-gnl|WGS:JAAGAX|GT039715.t1-3;Parent=rna-gnl|WGS:JAAGAX|GT039715.t1;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
CM021226.1	Genbank	exon	4306	4417	.	+	.	ID=exon-gnl|WGS:JAAGAX|GT039715.t1-4;Parent=rna-gnl|WGS:JAAGAX|GT039715.t1;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
CM021226.1	Genbank	exon	4651	4809	.	+	.	ID=exon-gnl|WGS:JAAGAX|GT039715.t1-5;Parent=rna-gnl|WGS:JAAGAX|GT039715.t1;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
CM021226.1	Genbank	exon	5006	5157	.	+	.	ID=exon-gnl|WGS:JAAGAX|GT039715.t1-6;Parent=rna-gnl|WGS:JAAGAX|GT039715.t1;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
CM021226.1	Genbank	exon	5396	5600	.	+	.	ID=exon-gnl|WGS:JAAGAX|GT039715.t1-7;Parent=rna-gnl|WGS:JAAGAX|GT039715.t1;gbkey=mRNA;locus_tag=GH714_038397;orig_protein_id=gnl|WGS:JAAGAX|GT039715.t1.cds7;orig_transcript_id=gnl|WGS:JAAGAX|GT039715.t1;product=hypothetical protein
grep: write error
cat: write error: Broken pipe
[1] 0
found 226568 gff entires           chr start   end           id strand ord
 1: CM021226.1  3335  3537 KAF2299603.1      +   1
 2: CM021226.1  3903  3965 KAF2299603.1      +   2
 3: CM021226.1  4098  4214 KAF2299603.1      +   3
 4: CM021226.1  4306  4417 KAF2299603.1      +   4
 5: CM021226.1  4651  4809 KAF2299603.1      +   5
 6: CM021226.1  5006  5157 KAF2299603.1      +   6
 7: CM021226.1  5396  5600 KAF2299603.1      +   7
 8: CM021226.1 19847 19851 KAF2299602.1      -   8
 9: CM021226.1 19977 20412 KAF2299602.1      -   9
10: CM021226.1 24001 24238 KAF2299601.1      +  10
, and 226568 CDS entries

**FOUND DUPLICATE GFF ENTRIES. THERE COULD BE A PROBLEM*** 
subsetting to longest model for each gene
		Importing fasta ...  [1] "KAF2281628.1 hypothetical protein GH714_043943 [Hevea brasiliensis]"
 [2] "KAF2281629.1 hypothetical protein GH714_043944 [Hevea brasiliensis]"
 [3] "KAF2281630.1 hypothetical protein GH714_043934 [Hevea brasiliensis]"
 [4] "KAF2281631.1 hypothetical protein GH714_043935 [Hevea brasiliensis]"
 [5] "KAF2281632.1 hypothetical protein GH714_043936 [Hevea brasiliensis]"
 [6] "KAF2281633.1 hypothetical protein GH714_043937 [Hevea brasiliensis]"
 [7] "KAF2281634.1 hypothetical protein GH714_043938 [Hevea brasiliensis]"
 [8] "KAF2281635.1 hypothetical protein GH714_043939 [Hevea brasiliensis]"
 [9] "KAF2281636.1 hypothetical protein GH714_043940 [Hevea brasiliensis]"
[10] "KAF2281637.1 hypothetical protein GH714_043941 [Hevea brasiliensis]"
found 44146 fasta entires
 [1] "KAF2281628.1" "KAF2281629.1" "KAF2281630.1" "KAF2281631.1" "KAF2281632.1"
 [6] "KAF2281633.1" "KAF2281634.1" "KAF2281635.1" "KAF2281636.1" "KAF2281637.1"
		44146 gff-peptide matches
	Done!
`
Apologies if I am totally off-base or if this is a personal issue of not understanding the parsing function arguments.  Thanks very much for your help!! 

Best, 
Arielle

**Comment by jtlovell** [comment]
Hi Arielle, 
This is maybe the hardest part of GENESPACE and the place we get the most questions. Since there are so many versions of gff files, it can be hard to figure out how to parse correctly. Can you either attach your gff and peptide annotation files here or send them to my email (if you don't want to share them publicly)? I'll troubleshoot and post the correct parameterization here ... that is unless there is a bug elsewhere like you suggest, in which case I'll fix and push asap. 
Cheers, 
John

**Comment by ariellerjohnson** [comment]
For Hevea, I just got the files from NCBI: 
#NCBI Bioproject is here https://www.ncbi.nlm.nih.gov/bioproject/PRJNA587314
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/458/925/GCA_010458925.1_ASM1045892v1/GCA_010458925.1_ASM1045892v1_protein.faa.gz
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/010/458/925/GCA_010458925.1_ASM1045892v1/GCA_010458925.1_ASM1045892v1_genomic.gff.gz
gunzip *.*
mv GCA_010458925.1_ASM1045892v1_genomic.gff GCA_010458925.1_ASM1045892v1_genomic.gff3

**Comment by ariellerjohnson** [comment]
Jatropha too! (I realized my command includes that plant as well): 
#Got from here: https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/180498/102/
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/180498/102/GCF_014843425.1_RJC1_Hi-C/GCF_014843425.1_RJC1_Hi-C_protein.faa.gz
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/180498/102/GCF_014843425.1_RJC1_Hi-C/GCF_014843425.1_RJC1_Hi-C_genomic.gff.gz
gunzip *.gz
mv GCF_014843425.1_RJC1_Hi-C_genomic.gff GCF_014843425.1_RJC1_Hi-C_genomic.gff3

**Comment by jtlovell** [comment]
There are two things - 
First, I think the Havea parsing didn't work right. Wow. That Havea annotation is ... very unique. See the code below needed to parse it correctly. 
Second, you should be using the translated_cds files instead of the protein files. For example: https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/180498/102/GCF_014843425.1_RJC1_Hi-C/GCF_014843425.1_RJC1_Hi-C_translated_cds.faa.gz

I didn't run these through GENESPACE, so if there is a downstream problem (like a mismatch in the gffs), please post here. I won't close this issue out. 

This is the annotation parameterization that worked for me:
```
parse_ncbi(gsParam = gpar, genomeIDs = "jatropha")
Parsing annotations: jatropha
	Reading gff ... found 19414 protein coding genes
	Reading peptide fasta ... found 29586 / 19414 total and unique entries
	Merging fa and gff found 19385 matching entires


parse_annotations(
  gsParam = gpar, genomeIDs = "havea", troubleshoot = F, 
  gffEntryType = "CDS", gffIdColumn = "protein_id", headerStripText = ".*=|]")

Parsing annotation files ...
	havea ... 
		Importing gff ... found 226568 gff entires, and 226568 CDS entries

**FOUND DUPLICATE GFF ENTRIES. THERE COULD BE A PROBLEM*** 
subsetting to longest model for each gene
		Importing fasta ... found 44146 fasta entires

**FOUND DUPLICATE PEPTIDE FASTA HEADERS. IS THIS JUST A PRIMARY TRANSCRIPT FILE?*** 
subsetting to longest model for each gene
		42449 gff-peptide matches
	Done!
```

**Comment by ariellerjohnson** [comment]
Hi John, 

Tried the translated_cds and used your parsing code-- the parsing ran smoothly (thanks!!) but Hevea still ended up with an "nbp" column in the gff and Jatropha ended up without one.  Then when I tried to run the synteny I got the same error.  
Error in rbindlist(lapply(names(gffFiles), function(i) { : 
  Item 2 has 7 columns, inconsistent with item 1 which has 8 columns. To fill missing columns use fill=TRUE.

My R script is below in case it's helpful.  Thanks so much!!

`##Troubleshooting GENESPACE, continued
#Arielle Johnson 2/23/22

library("GENESPACE")

gpar <- init_genespace(
  genomeIDs = c("Hevea brasiliensis", "Jatropha curcas"),
  speciesIDs = c("HeveaBrasiliensis", "JatrophaCurcas"),
  versionIDs = c( "v", "v"),
  ploidy = c(1,1),
  wd = "/workdir/arj66/GENESPACE/E_peplus_GENESPACE/Euphorbiaceae",
  orthofinderMethod = "fast",
  diamondMode = "fast",
  nCores = 20,
  gffString = "gff3",
  pepString = ".fa",
  path2mcscanx = "/programs/MCScanX",
  rawGenomeDir = "/workdir/arj66/GENESPACE/E_peplus_GENESPACE/genomes/")


parse_ncbi(gsParam = gpar, genomeIDs = "Jatropha curcas", overwrite = T)

parse_annotations(
  gsParam = gpar, genomeIDs = "Hevea brasiliensis", troubleshoot = F, 
  gffEntryType = "CDS", gffIdColumn = "protein_id", headerStripText = ".*=|]", 
  overwrite = T)

gpar <- run_orthofinder(gsParam = gpar, overwrite = T)
gpar <-  synteny(gsParam=gpar, overwrite = T)
`

Thanks,
Arielle

**Comment by jtlovell** [comment]
Yes, you are right. The nbp column was left on the parse_annotations function. I have stripped this off in a bug fix I just pushed. It runs through on those two genomes for me now. Please let me know if this fixed it. 
Just a heads up, it doesn't look like Jatropha is chromosome scale ... I'm not 100% sure that GENESPACE will be appropriate for analyzing it, depending on how contiguous the genic regions are.
Thanks!!!
John

**Comment by ariellerjohnson** [comment]
John, 

Great, with the bug fixed it's working for me now.  Thanks very much!!

Best, 
Arielle

**Comment by jtlovell** [comment]
Great! Really appreciate your effort working through these growing pains for GENESPACE.
