### ISSUE TITLE
Clarify 'integer string'

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [jtlovell/GENESPACE#60]
Hi,

the Overview, section 3.1 uses the term 'integer string' for the ploidy value. This is a bit confusing in that it is not a data type. Is the value a tuple of strings that must be an integer, or a string that contains integers separated by commas. The example of ploidy <-rep(1,3), gives [1] 1 1 1, which is not the same as ploidy <- "1,1,1" which gives [1] "1,1,1".

Thanks.

**Comment by jtlovell** [comment]
thats a typo - integer vector.

**Comment by theo-allnutt-bioinformatics** [comment]
Thanks.
