### ISSUE TITLE
Chromosomes scaled by gene rank order explanation

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [jtlovell/GENESPACE#62]
Hi,

could you please explain a little further the meaning of "Chromosomes scaled by gene rank order" as shown on the riparian plots?
I have two genomes 'nm' and 'ft' of ~1Gbp and ~0.5Gbp respectively, the orthogroups in stdout were:
		ft: 5675 genes in 2181 collinear arrays
		nm: 7100 genes in 1145 collinear arrays
I would therefor expect the scale of 'nm' to be larger' but it is the opposite. See figure attached.

Thanks very much,

Theo
[Rplots.pdf](https://github.com/jtlovell/GENESPACE/files/10462101/Rplots.pdf)

**Comment by theo-allnutt-bioinformatics** [comment]
I should add, both assemblies are effectively chromosome level, nm = 67 contigs; ft = 8 contigs. nm is less complete and some contigs may need further scaffolding, but we expect nm to have many more chromosomes than ft (possibly from many ancient duplications).

**Comment by jtlovell** [comment]
I hope the gene rank order q is answered in detail in the genespace publication methods - its the order of genes. Those numbers are related to the size of the arrays, not the number of genes, which are reported when `init_genespace` qc's your genomes.
