### ISSUE TITLE
Advice on diverged genomes and paralogy

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [jtlovell/GENESPACE#63]
Hi,

I have some order-level plant genomes to compare. Can you advise on parameters which might help detect more diverged synteny? The guide mentions they need to be tuned but does not give examples. I also think that in my case, I would like to see paraology - which may have led to duplications in the group - this is an important evolutionary aspect. I assume that nSecondHits=1 would achieve this and that unless specified, parameters ending in 'second' are default? However, would nhits > 1 also achieve this?

Thanks,

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
N.B. the nhits= option gives an error:

Error in set_syntenyParams(gsParam = gpar, blkSize = 3, onlyOgAnchors = F,  : 
  unused arguments (nhits1 = 10, nhits2 = 10)
Execution halted

**Comment by jtlovell** [comment]
Hi Theo - there is a detailed section in the genespace [manuscript](https://elifesciences.org/articles/78526.pdf) on how to properly handle paralogs. Give that a read and if things are still unclear, let me know specifically whats up. 
Look at `?set_syntenyParams` nhits1/2 is not a parameter there. How nhits is specified is detailed in the manuscript.
