### ISSUE TITLE
path for diamond 

### ISSUE THREAD

**Issue by jdobry-lab** [jtlovell/GENESPACE#74]
Hi John,

In the old version I could designate the path for orthofinder and diamond separately.  However, in this version, I cannot do that. The orthofinder version 2.5.4 still has the old version of diamond as it's dependency and I downloaded the newer version of diamond separately and used cMake to compile it and it was working fine. However with the latest version of genespace, I cannot seem to get orthofinder to run with the lastest install for diamond.

Any ideas how to fix this?

Thanks,
Jason

**Comment by jtlovell** [comment]
Hi Jason, 
I'm assuming you were using `orthofinderMethod = "fast"` before, is that right? If so, this entire routine has been dropped from GENESPACE ... it was the main source of issues in v0.9x and became too difficult to maintain. Now, the only option is to get an up-to-date orthofinder install. Sorry I can't be of more help.
John

**Comment by jtlovell** [comment]
I'm gonna close this, but let me know if you run into problems with an updated install.
