### ISSUE TITLE
Error in setnames(ogs, c("pgRepID", "ofID")) : Can't assign 2 names to a 0 column data.table

### ISSUE THREAD

**Issue by em255** [jtlovell/GENESPACE#77]
Trying to get up to speed on V1.  I decided to manually parse my annotations to create bed and peptide files that (pretty much) 100% overlap.  Got through a lot of the orthofinder and synteny steps then keep getting this error:
[jobname.txt](https://github.com/jtlovell/GENESPACE/files/11054379/jobname.txt)

Here is my small command script for reference:
`library(GENESPACE)
gpar <- init_genespace(
  genomeIDs = c("CassavaV8","Col1010Bhap1","Col1010Bhap2","Col1484hap1","Col856hap1","Col875hap1","Col875hap2","Col282hap2","Col282hap1","Col856hap2","Col1484hap2"),
  speciesID = c("CassavaV8","Col1010Bhap1","Col1010Bhap2","Col1484hap1","Col856hap1","Col875hap1","Col875hap2","Col282hap2","Col282hap1","Col856hap2","Col1484hap2"),
  versionID = c("CassavaV8","Col1010Bhap1","Col1010Bhap2","Col1484hap1","Col856hap1","Col875hap1","Col875hap2","Col282hap2","Col282hap1","Col856hap2","Col1484hap2"),
  ploidy = rep(1,11),
  wd = "~/path/tp/V1test2",
  path2mcscanx = "~/path/to/MCScanX",
  path2diamond= "~/mambaforge/envs/orthofinder/bin/diamond")
gpar <- run_genespace(gsParam = gpar)
`

Thanks for any help

**Comment by jtlovell** [comment]
Thanks! This looks like a bug. 
Would you mind sharing your /bed and /peptide directories? If so, ping me via email or twitter DM and I'll set up a transfer.

**Comment by em255** [comment]
KK I'll tar it all up and I can send it how you'd like it.
Evan

**Comment by em255** [comment]
It's only ~100Mb

**Comment by jtlovell** [comment]
OK - this was a bug. Your orthofinder run did not produce any orthologue files, which is unexpected, but should be fine. Now, GENESPACE checks for whether the ortholog files exist and if they do not, it doesn't try to parse them and does not include non-syntenic orthologs in the pan-gene set. Updates have been pushed to master v1.1.8.

**Comment by em255** [comment]
Thanks, I'll test it out
