### ISSUE TITLE
parse_annotation

### ISSUE THREAD

**Issue by nirwan1265** [jtlovell/GENESPACE#78]
I am getting this error while running parse_annotation:
> parsedPaths <- parse_annotations(
+   rawGenomeRepo = genomeRepo,
+   genomeDirs = c("maize_phytozome","sorghum_phytozome"),
+   genomeIDs = c("maize","sorghum"),
+   gffString = "gff3",
+   faString = "fa",
+   presets = "phytozome",
+   genespaceWd = "/Users/nirwantandukar/Downloads/GENESPACE/workingDirectory")
Error: subscript contains invalid names

These are my folders:
genomeRepo <- "/Users/nirwantandukar/Downloads/GENESPACE/data"
... /data
       - maize_phytozome
             - maize.fa
             - maize.gff3
        - sorghum_phytozome
             - sorghum.fa
             - sorghum.gff3

genespaceWd = "/Users/nirwantandukar/Downloads/GENESPACE/workingDirectory
..../workingDirectory
     - bed
        - maize.bed
        - sorghum.bed
     - peptide
        - maize.fa
        - sorghum.fa
 
 These are how my bed files and peptide fasta files look:
 
<img width="265" alt="Screen Shot 2023-03-24 at 12 03 15 PM" src="https://user-images.githubusercontent.com/88001815/227579100-694c44c0-3c20-46ee-8c82-e8f305d150ab.png">

<img width="406" alt="Screen Shot 2023-03-24 at 12 03 38 PM" src="https://user-images.githubusercontent.com/88001815/227579190-c2116489-ec0f-4fee-8647-f71732b29506.png">

These are how my gff3 and fa nt seq look:
<img width="1095" alt="Screen Shot 2023-03-24 at 12 06 45 PM" src="https://user-images.githubusercontent.com/88001815/227579891-99a0fe97-5eb7-4bec-8044-f840bd1a9ffb.png">

<img width="444" alt="Screen Shot 2023-03-24 at 12 07 07 PM" src="https://user-images.githubusercontent.com/88001815/227579972-09762f74-37e2-4698-bb4a-f3ec54e689f4.png">

Is there a problem if I use different isoforms for the gene?
I just keep getting the Error: subscript contains invalid names

**Comment by jtlovell** [comment]
Well, I think you need two separate `parse_annotations` calls then ... `parse_annotations(..., presets = "phytozome")` only parses phytzome-formatted annotations (sorghum here). You'll need to build out the parameters needed to parse the maizegdb formats separately and only give that call the maize genome. You can also download from NCBI and use `parse_annotations(... presets = "ncbi")` for the most recent maize genome. See the readme or tutorial for more info.

**Comment by nirwan1265** [comment]
It is working now. thanks

**Comment by alexvasilikop** [comment]
Hello,

I have the same problem but my gff annotations are generated manually from the output of gene predictions.
The structure is the following:

WorkingDir/species1/species1.fa
WorkingDir/species1/species1.gff

WorkingDir/species2/species2.fa
WorkingDir/species2/species2.gff

This is how the gff looks
Chrom_6	GenBank	gene	13854192	13854781	.	-	.	locus=FUN_031356
Chrom_6	GenBank	gene	13854839	13856211	.	+	.	locus=FUN_031357
Chrom_6	GenBank	gene	13863665	13863955	.	-	.	locus=FUN_031358
Chrom_6	GenBank	gene	13866384	13872011	.	-	.	locus=FUN_031359
Chrom_6	GenBank	gene	13874794	13875030	.	+	.	locus=FUN_031360
Chrom_6	GenBank	gene	13878012	13879325	.	+	.	locus=FUN_031361
Chrom_6	GenBank	gene	13880772	13881455	.	-	.	locus=FUN_031362
Chrom_6	GenBank	gene	13881782	13882003	.	+	.	locus=FUN_031363
Chrom_6	GenBank	gene	13886437	13888282	.	-	.	locus=FUN_031364
Chrom_6	GenBank	gene	13889422	13890531	.	+	.	locus=FUN_031365


The documentation is a bit confusing about whether someone should use gff or bed for starters. How can I parse the annotations using custom bed files?

the error I get is the following:
´´´
Error: subscript contains invalid names
´´´

thanks

**Comment by alexvasilikop** [comment]
Ok apparently, if you provide the bed and fasta files you don't need to parse anymore.
So problem solved
