### ISSUE TITLE
Step 3:  Combining and annotating the blast files with orthogroup info error

### ISSUE THREAD

**Issue by rac266** [jtlovell/GENESPACE#83]
Hello,

Thanks for creating Genespace! My current Genespace run is failing at step 3. I ran into the issue before with my previous version of genespace (v1.1.4), and after reading similar issues (#70 and #81) I downloaded the most recent version (v1.1.9) but am still running into the same error. Also, all created folders have output except for the riparian and dotplot folders.

> library(GENESPACE)
> gpar <- init_genespace(
+ wd = "/path/to/workingDir",
+ path2mcscanx = "/path/to/MCScanX/")
Checking Working Directory ... PASS: `/path/to/workingDir`
Checking user-defined parameters ...
        Genome IDs & ploidy ...
                species1_AstMex3_surface_GCA_023375975.1: 1
                species2_AstMex3_Molino_GCA_023375845.1 : 1
                species3_AstMex3_Tinaja_GCA_023375835.1 : 1
                species4_AMEX_1.1_GCA_019721115.1       : 1
        Outgroup ... NONE
        n. parallel processes ... 14
        collinear block size ... 5
        collinear block search radius ... 25
        n gaps in collinear block ... 5
        synteny buffer size... 100
        only orthogroups hits as anchors ... TRUE
        n secondary hits ... 0
Checking annotation files (.bed and peptide .fa):
        species1_AstMex3_surface_GCA_023375975.1: 27065 / 27065 geneIDs exactly match (PASS)
        species2_AstMex3_Molino_GCA_023375845.1 : 26293 / 26293 geneIDs exactly match (PASS)
        species3_AstMex3_Tinaja_GCA_023375835.1 : 27295 / 27295 geneIDs exactly match (PASS)
        species4_AMEX_1.1_GCA_019721115.1       : 27244 / 27244 geneIDs exactly match (PASS)
Checking dependencies ...
        Found valid path to OrthoFinder v2.54: `orthofinder`
        Found valid path to DIAMOND2 v2.16: `diamond`
        Found valid MCScanX_h executable: `/path/to//MCScanX//MCScanX_h`
> gpar <- run_genespace(gsParam = gpar)

############################
1. Running orthofinder (or parsing existing results)
        Checking for existing orthofinder results ...
        ... found existing run, not re-running orthofinder

############################
2. Annotated/concatenated bed file exists

############################
3. Combining and annotating the blast files with orthogroup info ...
        # Chunk 1 / 1 (01:43:15 PM) ...
Error in rbindlist(mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  Item 1 of input is not a data.frame, data.table or list
In addition: Warning message:
In mclapply(1:nrow(chnk), mc.cores = nCores, function(i) { :
  all scheduled cores encountered errors in user code

Also, example headers for both the peptide and bed files are below:

head species1_AstMex3_surface_GCA_023375975.1.bed 
1 45362 56004 ENSAMXG00025000236
1 64624 101667 ENSAMXG00025000257
1 103026 114134 ENSAMXG00025000258
1 123301 137874 ENSAMXG00025000259

head species1_AstMex3_surface_GCA_023375975.1.fa 
>ENSAMXG00025000109
CVRHDSHQVFGAFSSDPFRVSNSCYGTGETFLFTFDPEFKTFCWSGENSYFVRGFLDSLQ
MGGGGGGPFGLWLDADLCRGSTFSCNTFRNQPLSPLQDFTIRAVEVWTFL
>ENSAMXG00025000110

**Comment by jtlovell** [comment]
ok! new error. 
can you re-run with just one core `init_genespace(nCores = 1,...)` and post the output? This will produce a more informative error. 
To help troubleshoot, if you are ok with it, would you mind sharing your input /bed and /peptide directories? If so, email (jlovell[at]hudsonalpha.org) or dm me on twitter and I'll send the link

**Comment by rac266** [comment]
Sounds good, thanks! I will send the files to your email. Below is the error with just 1 core:

3. Combining and annotating the blast files with orthogroup info ...
Error in fwrite(x, file = filepath, showProgress = F, quote = F, sep = "\t") : 
  Compression in fwrite uses zlib library. Its header files were not found at the time data.table was compiled. To enable fwrite compression, please reinstall data.table and study the output for further guidance.

**Comment by jtlovell** [comment]
hmmm. that sounds like a pretty straightforward issue ... can you try to re-install data.table?

**Comment by rac266** [comment]
Ah I see. Good news is updating data.table worked. Thank you! The plots look great.

**Comment by rac266** [comment]
Thanks for your help! Updating data.table worked, and I now have the final plots.

Regards,


Rachel Carroll


Research Specialist | Laboratory Manager

Department of Animal Sciences

Christopher S. Bond Life Sciences Center - University of Missouri

***@***.***

816-769-1124

________________________________
