### ISSUE TITLE
Error in if (is.na(gsParam$synteny$hogs))

### ISSUE THREAD

**Issue by xiaoyezao** [jtlovell/GENESPACE#85]
Hi,

I got the following error in GENESPACE v1.2: 

```
1. Running orthofinder (or parsing existing results)
	Checking for existing orthofinder results ...
	... found existing run, not re-running orthofinder
Error in if (is.na(gsParam$synteny$hogs)) { : argument is of length zero
Calls: run_genespace
Execution halted
```

I run orthofinder independently and used the `-y option (Split paralogous clades below root of a HOG into separate HOGs)`. Could this be the issue?

Thank you.

**Comment by jtlovell** [comment]
I have not written anything to support `orthofinder -y` and I don't plan to. Does it run using the default method? If not, I'll check and see what might be causing this.

**Comment by jtlovell** [comment]
I'm going to close this, but re-open if you have issues. 
John
