### ISSUE TITLE
exclude some chromosomes in riparian plotting

### ISSUE THREAD

**Issue by xiaoyezao** [jtlovell/GENESPACE#88]
Hi John,

How do I exclude some chromosomes in riparian plotting? I find in some genome assemblies there is a Chr0 which is an artificial one by combining unanchored contigs.  I want to include these in Orthofinder but leave them out in the plotting.

<img width="744" alt="Screenshot 2023-05-01 at 10 02 44" src="https://user-images.githubusercontent.com/44076439/235426503-86e0716f-e8ba-40c7-9a7f-82a5e8a0235b.png">

**Comment by jtlovell** [comment]
Short answer, no, you can't exclude chromosomes ... you can use the `plot_riparian(..., highlightBed = data.frame, ...)`argument to specify regions of interest and supply it with all the non-chr0 chrs, but this will not necessarily be accurate. 

Also, I would highly recommend not building genomes this way - combining unscaffolded contigs into a pseudo-scaffold. Its a problem for many reasons downstream (this is one of them). You can still recover this analysis though ... I'd suggest splitting the chr0's into their contigs (should be easy to do with N's in the gaps), re-building the gff with the split contigs gene coordinates and re-running genespace. The orthofinder run should not need to be changed.
