### ISSUE TITLE
Can't find valid path to the MCScanX_h executable

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [jtlovell/GENESPACE#94]
Even though I set the path:

path2mcscanx <- "/my/actual/path/bin/MCScanX/"
or
path2mcscanx <- "/my/actual/path/bin/MCScanX"

I get this warning:

**WARNING!!** Can't find valid path to the MCScanX_h executable in
        `MCScanX`.  Only plotting and query GENESPACE functions will be
        functional. If you want to run the main `synteny` function, you
        will need to specify a path to a valid MCScanX installation
        (see README).

MCScanX_h is definitely in the specified directory.

**Comment by theo-allnutt-bioinformatics** [comment]
/my/actual/path/bin/MCScanX is also in my PATH and MCSscaX and MCScan_h both run fine from command line.

**Comment by theo-allnutt-bioinformatics** [comment]
ok, I didn't have path2mcscanx = path2mcscanx in my init_genespace statement. Solved.

**Comment by kipdlacy** [comment]
I am getting this same error message, but unlike with theo-allnutt-bioinformatics, I do specify the path2mcscanx path in my init_genespace statement. I'm confused about how to resolve this issue. I used the following code: 

gpar <- init_genespace(wd = "./",
                       path2mcscanx = "./MCScanX/")

And received the below error message.

**WARNING!!** Can't find valid path to the MCScanX_h executable in `./MCScanX/`.  Only plotting and
        query GENESPACE functions will be functional. If you want to run the main `synteny` function,
        you will need to specify a path to a valid MCScanX installation (see README).
