### ISSUE TITLE
Stuck at step 3.

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [jtlovell/GENESPACE#98]
My run seems to hang at step 3. No files updated in results/ for 2.5 hours..

3. Combining and annotating the blast files with orthogroup info ...
        # Chunk 1 / 1 (13:46:59) ...

Using latest version.
Script:

```
library(GENESPACE)

wd <-"/g/data/nm31/d/r17_nepenthes/r17.2_synteny/gs2/"

path2mcscanx <- "/g/data/nm31/bin/MCScanX/"

genomes2run <- c("nm","ft","bv","so")

gpar <- init_genespace(
  genomeIDs = genomes2run,
  wd = wd,
  nCores = 48,
  blkSize=3,
  onlyOgAnchors=F,
  nSecondHits=10,
  path2mcscanx = path2mcscanx)

out <- run_genespace(gpar, overwrite = T)
```

**Comment by theo-allnutt-bioinformatics** [comment]
[genespace.zip](https://github.com/jtlovell/GENESPACE/files/11484743/genespace.zip)
data

**Comment by jtlovell** [comment]
Those are some strange parameters. Does it run without all that and `nCores = 1`?

**Comment by jtlovell** [comment]
I just pushed it through with defaults without a problem. 
But these genomes look pretty problematic and you may want to do some QC first ... For example, `bv` has a huge bottom drawer and a huge amount of off-diagonal orthogroup hits. `nm` has two scaffolds that are entirely a single array and essentially no synteny, `so` is not scaffolded and is probably too split up for synteny to be useful.

**Comment by theo-allnutt-bioinformatics** [comment]
It's a fringe case. Yes it worked on a PBS job in ~2 hours. I think it was throttled previously and couldn't close a thread.
